### ISSUE TITLE
Add recipe for source install

### ISSUE THREAD

**Issue by clofresh** [DataDog/chef-datadog#107]

**Comment by miketheman** [comment]
@asiegman Since the opening of this issue, we have released version 5.x of the Datadog Agent, which bundles a self-contained supervisor which no longer conflicts with any other installed supervisor.
With that, you'd likely no longer need the source install method.

**Comment by miketheman** [comment]
Closing out this issue, as there's packagers for systems that no longer interfere with other supervisors.
