### ISSUE TITLE
Add HTTP and TCP Check recipes

### ISSUE THREAD

**Issue by conorbranagan** [DataDog/chef-datadog#110]
See https://github.com/DataDog/dd-agent/blob/master/conf.d/http_check.yaml.example
and https://github.com/DataDog/dd-agent/blob/master/conf.d/tcp_check.yaml.example

**Comment by xbeta** [comment]
why can't we merge this??
+1 for needing this to work

**Comment by miketheman** [comment]
@xbeta this is the next check to be worked on.

**Comment by miketheman** [comment]
Code is now merged to master!

**Comment by xbeta** [comment]
@miketheman 
Awesome! when can I expect a release?  We prefer not pin our datadog cookbook version to master HEAD

**Comment by miketheman** [comment]
Targeting April 20th for release.
