### ISSUE TITLE
Add support for docker monitoring

### ISSUE THREAD

**Issue by danielmcgrath** [DataDog/chef-datadog#139]
Per: https://www.datadoghq.com/2014/06/monitor-docker-datadog/

Sample configuration: https://github.com/DataDog/dd-agent/blob/master/conf.d/docker.yaml.example

**Comment by miketheman** [comment]
@DorianZaccaria Please create a new recipe, template, serverspec test according to current patterns and send a PR.

**Comment by miketheman** [comment]
Should also resolve and future-proof #150, using the new json->yaml style so as not to specify each key:value when the agent changes.

**Comment by DorianZaccaria** [comment]
Here a Pull Request: https://github.com/DataDog/chef-datadog/pull/197

**Comment by miketheman** [comment]
Merged #197, closing.
