### ISSUE TITLE
Request: Support Windows agent installation

### ISSUE THREAD

**Issue by rlaveycal** [DataDog/chef-datadog#142]
Hi,

Do you plan to support installation of the Windows agent?

**Comment by err0** [comment]
here is what I ended up doing:

```ruby
# Datadog agent
case node['platform_family']
when 'debian'
  include_recipe 'datadog::dd-agent'
when 'rhel'
  include_recipe 'datadog::dd-agent'
when 'windows'
  remote_file 'C:\ddagent-cli.msi' do
    source 'https://s3.amazonaws.com/ddagent-windows-stable/ddagent-cli.msi'
  end
   # APIKEY option is mandatory
   # TAGS and HOSTNAME are optional values.
  windows_package 'ddagent-cli' do
    action :install
    source 'C:\ddagent-cli.msi'
    options 'TAGS="sometags" ' + 'APIKEY=' + dd__databag_creds['api_key']
  end
end
```

Perhaps something like this could be easily incorporated in to the community cookbook?

**Comment by EasyAsABC123** [comment]
@err0 yeah I think that isn't a bad plan, should probably delete the file and allow for a download location since `C:\` is normally protected.

I like it though, one more thing the `https://s3.amazonaws.com/ddagent-windows-stable/ddagent-cli.msi` doesn't allow for you to choose a version and stay on it, instead you are always going to be grabbing the latest and even though it says stable are you willing to risk multiple production nodes on it?

These were the questions I was forced to ask myself when I was writing this, basically support for windows with an eye on PCI, HIPAA, and SOX compliance.

**Comment by LeoCavaille** [comment]
@err0 @EasyAsABC123 it's not published on the website (maybe we should actually), but one can download _thus pin_ a specific version of the agent by using:
```https://s3.amazonaws.com/ddagent-windows-stable/ddagent-cli-<version>.msi```

Latest version is 5.3.1.

**Comment by err0** [comment]
@LeoCavaille good to know!
So if node['datadog']['agent_version'] is not null then plug it in the MSI filename with a leading -.

**Comment by rlaveycal** [comment]
We also need to consider upgrading the agent. The windows_package resource doesn't support this so something like this is required (based on #164). I support setting the download url to nil to disable auto-install.

```ruby
# Get latest or specific agent version
dd_agent_msi = node['datadog']['agent_version'].nil? ? 'ddagent-cli.msi' : "ddagent-cli-#{node['datadog']['agent_version']}.msi"
temp_file = "#{Chef::Config[:file_cache_path]}/ddagent-cli.msi"

# download to temp file
downloadMsi = remote_file temp_file do
  source 	"#{node['datadog']['agent_download_url']}#{dd_agent_msi}"
  not_if	{ node['datadog']['agent_download_url'].nil? }
end

#uninstall if new MSI downloaded
windows_package 'Datadog Agent' do
  action	:remove
  only_if	{ downloadMsi.updated_by_last_action? }
end

#install
windows_package 'Datadog Agent' do
  source	temp_file
  options 	"APIKEY=\"#{node['datadog']['api_key']}\""
  not_if	{ node['datadog']['agent_download_url'].nil? }
end
```

**Comment by bigbam505** [comment]
The windows client actually does support upgrading based on if you pass in a version.  Here is what I have setup for installing datadog on windows:
```ruby
# attributes/default.rb

default['datadog']['installer']['name'] = 'Datadog Agent'
default['datadog']['installer']['url'] = 'https://s3.amazonaws.com/ddagent-windows-stable/ddagent-cli-5.4.0.msi'
default['datadog']['installer']['checksum'] = 'a4da3c0c45511017a3d872b7a8ffee820642eaeeec3fd3f3fb34a589a4b59863'
default['datadog']['configs']['location'] = 'C:\\ProgramData\\Datadog'
default['datadog']['url'] = 'https://app.datadoghq.com'
default['datadog']['api_key'] = nil
default['datadog']['application_key'] = nil
default['datadog']['hostname'] = node['fqdn']
```
```
# recipes/dd-agent.rb

dd_agent_installer = ::File.join(Chef::Config[:file_cache_path], 'dd-agent.msi')

remote_file dd_agent_installer do
  source node['datadog']['installer']['url']
  checksum node['datadog']['installer']['checksum']
end

windows_package node['datadog']['installer']['name'] do
  action :install
  source dd_agent_installer
  version node['datadog']['installer']['version'] if node['datadog']['installer']['version']
  installer_type :msi
end

raise "Add a ['datadog']['api_key'] attribute to configure this node's Datadog Agent." if node['datadog'] && node['datadog']['api_key'].nil?

template "#{node['datadog']['configs']['location']}\\datadog.conf" do
  source "datadog.conf.erb"
end

windows_service 'DatadogAgent' do
  action [:enable, :start]
  subscribes :restart, "windows_package[#{node['datadog']['installer']['name']}]", :delayed
  subscribes :restart, "template[#{node['datadog']['configs']['location']}\\datadog.conf]", :delayed
end
```

Granted the `windows_service` part was added into chef 12 and there are weird inconsistencies with `windows_package` and the version that you pass in.

**Comment by rlaveycal** [comment]
Neat.

Also, be aware that the agent seems to be installed in per-user mode so you can't install as user X and then upgrade as user Y :(

I've raised DataDog/dd-agent#1689 to see if this can be tackled. Not a problem once you're using Chef to deploy and running as the same user, but is going to cause me grief as the agent is currently installed by a different user that I use for Chef so I'll have to manually uninstall.

**Comment by rlaveycal** [comment]
Referring back to my previous code, my recipe now does
````ruby
windows_package 'Datadog Agent' do
  source	temp_file
  options 	"APIKEY=\"#{node['datadog']['api_key']}\""
  version   "#{node['datadog']['agent_version']}.0" if node['datadog']['agent_version'] # installed version is x.y.z.0
  not_if	{ node['datadog']['agent_package_action'] == 'none' }
end
````

Note that the version passed into windows_package needs to have 4 parts, but the version passed to the url only has 3. Without the trailing .0 the package will be installed on every run as the version strings won't match

**Comment by rlaveycal** [comment]
It seems that DD have removed all historic versions of the agent from S3
