### ISSUE TITLE
Request: Add message / tags to dd-handler

### ISSUE THREAD

**Issue by rlaveycal** [DataDog/chef-datadog#143]
It would be useful to be able to include bespoke text and/or set additional tags to events created by the dd handler.
My specific use-case is that we have a release cookbook that defines the version of components installed. I want to include the version of that cookbook that is in the run list.

**Comment by miketheman** [comment]
Hi @rlaveycal,
Can you maybe explain a little further on how you'd like to do this?

Since the dd-handler already ensures that the dogapi gem is included, you could like use that to emit an Event to the Event Stream, instead of changing the current Chef Handler event.

**Comment by rlaveycal** [comment]
The thought was that it could be useful to include context information from the Chef run into the event. At present you get a list of all the resources that have been converged tags with the host and environment. That can be quite verbose. As I said above we have a specific cookbook version for each release we deploy. Being able to include that in the message and/or a tag would be useful in tying events together across servers.

Another way of looking at this would be to have an event resource that allowed you to easily create an event (wrap the dogapi gem) and to group those events with the handler events (complete with nice icon!). That way you can present user friendly messages at normal priority with the low priority "stack trace" handler events grouped under them.

**Comment by miketheman** [comment]
I think this is likely related to https://github.com/DataDog/chef-datadog/issues/145

**Comment by miketheman** [comment]
Closing in favor of using the Client API directly. See example here: https://github.com/DataDog/chef-datadog/issues/145#issuecomment-118511513
