### ISSUE TITLE
Feature: Event LWRP

### ISSUE THREAD

**Issue by MrMMorris** [DataDog/chef-datadog#145]
Just throwing an idea out there, but something like this for datadog events would be AMAZING!

https://github.com/cwjohnston/chef-hipchat

**Comment by miketheman** [comment]
I'm still unclear as to how this would be useful, vs using the Rubygem directly in Chef code.

Here's an example of sending an event directly from a recipe:
```ruby
require 'dogapi' # may not even be required if this recipe fires after datadog::dd-handler is loaded
dog = Dogapi::Client.new(node['datadog']['api_key'])

dog.emit_event(Dogapi::Event.new('Uh-oh, something bad happened',
                                 msg_title: "Alert from #{node.name}",
                                 alert_type: 'error',
                                 tags: ['ruby', node.environment]
                                 ))
```

You retain all the flexibility of the Event API, without making a resource/provider.

Is there any use case I'm not thinking about? Would a resource that provides the syntax into a "you can only submit events that look like this" be beneficial? How and why?

**Comment by MrMMorris** [comment]
Hi @miketheman,

Your solution would work. Thanks!
