### ISSUE TITLE
MongoDB config provides limit username/password support

### ISSUE THREAD

**Issue by msaffitz** [DataDog/chef-datadog#146]
The template for the MongoDB agent only supports host and port, and doesn't permit setting username, password, or database.  As a workaround, you can mash them into the host and port settings, but that's not super ideal.

It'd be great/simple if if just took the connection string.  Otherwise explicitly support user, pass, db.

templates/default/mongo.yaml.erb

**Comment by miketheman** [comment]
@msaffitz So what would a good alternate be? Allow setting an `instances` value of `connection_string` which would be an arbitrary string?
```ruby
connection_string = "mongodb://datadog:#{Chef::EncryptedDataBagItem.load('credentials', 'datadog')['mongo_pass']}@localhost:27017/database_name

 datadog: {
    mongo: {
      instances: [{
        connection_string: connection_string
      }]
    }
  }
```

**Comment by msaffitz** [comment]
Yeah, I think either as you've suggested, or have each element of the connection string be an option:

```
username = "datadog"
password = Chef::EncryptedDataBagItem.load('credentials', 'datadog')['mongo_pass']
hostname = "localhost"
port = 27017
db_name = "database_name"

 datadog: {
    mongo: {
      instances: [{
          username: username,
          password: password,
          hostname: hostname,
          port: port,
          db_name: db_name
      }]
    }
  }
```
