### ISSUE TITLE
dd-agent package does not upgrade when previously installed

### ISSUE THREAD

**Issue by uduncanu** [DataDog/chef-datadog#147]
We've got a load of servers where the dd-agent package (4.3.1-522) was previously installed via Chef (v10) with this cookbook.  We are attempting to upgrade it to the latest version, using the dd-agent recipe.  It isn't upgrading to the latest version on its own.

The only part of the recipe I can see that would actually perform an upgrade is the package command  included below, which requires `dd_agent_version` to be the latest version that we're trying to install, however that's set to nil in the default attributes file.  The end result is that it's essentially not specifying the version to install.

The default action with the package command is `:install`, and as there's already a version installed and no version specified, Chef doesn't take any further action, and so the dd-agent package doesn't get upgraded.

attributes/default.rb:
```
default['datadog']['agent_version'] = nil
```

recipes/dd-agent.rb:
```
dd_agent_version = node['datadog']['agent_version']
...
  package 'datadog-agent' do
    version dd_agent_version
  end
```

**Comment by miketheman** [comment]
Fixed in b8518fd582bf5d6a414a08a4d981200ccbc215d3
