### ISSUE TITLE
cannot set ec2_collect_tags via chef aws opsworks install

### ISSUE THREAD

**Issue by mirceal** [DataDog/chef-datadog#158]
I have 2 opsworks stack and in order for me to differentiate between them I need to be able to collect the ec2 tags associated with the machine.
if I manually set 
collect_ec2_tags: no
in /etc/dd-agent/datadog.conf I can see the tags being collected.

When I run the chef recipe via opsworks though, I don't see this parameter being configured in datadog.conf 
Looking at the template erg seems that the param is not there.

Added ['datadog']['collect_ec2_tags'] and ['datadog']['api_key'] to the custom json used by opsworks and the api_key is picked up just fine (i see it ending up in config) but the collect_ec2_tags is just ignored.

Need to find a way to add collecting the ec2 tags in config when the agent is installed via chef (or an workaround)

**Comment by miketheman** [comment]
PR has been merged, missed the link to this issue. Closing!

**Comment by xbeta** [comment]
@miketheman when can we expect newer release with this change?  We are at v2.0.0 now

**Comment by miketheman** [comment]
Targeting April 20th.
