### ISSUE TITLE
dd-handler can't send events on Windows due to missing SSL_CERT_FILE env var

### ISSUE THREAD

**Issue by rlaveycal** [DataDog/chef-datadog#165]
The openSSL gem used by the dd-handler requires that the SSL_CERT_FILE environment variable is set so that it can find the certificate store to validate the server's cert. On Windows this is not set by default so the handler fails.

In Chef 11.16, SSL_CERT_FILE is set for Chef components (see https://github.com/opscode/omnibus-chef/pull/236) but the dd-handler doesn't see/use it.

**Comment by err0** [comment]
https://github.com/chef/chef-dk/issues/106 had this issue too.

**Comment by bigbam505** [comment]
I added documentation on the dd-hadler site you can fix this with the following:

https://github.com/DataDog/chef-handler-datadog#windows-support

**Comment by miketheman** [comment]
Closing, in favor of documentation update.
