### ISSUE TITLE
Shouldn't node['datadog']['tags'] be an array or hash?

### ISSUE THREAD

**Issue by chrissnell** [DataDog/chef-datadog#170]
In the datadog.conf.erb template, I see that node['datadog']['tags'] is a string.  How do y'all feel about changing this attribute to an array or hash so that tags could be added by other cookbooks dynamically without overwriting tags set elsewhere.   The template could just do a .each to build the tag line in the configuration file.

Presumably the template could check the type of the attribute and do the right thing if the attribute is a string to retain backwards compatibility.

**Comment by miketheman** [comment]
Hey @chrissnell,

You bring up a good point.

I guess we didn't look at the use case too hard back when it was submitted.
One _could_ go about appending to a String, but that might not be great with commas and such.

I'm curious to see what you would have in mind.

**Comment by awasilyev** [comment]
Any updates?

**Comment by miketheman** [comment]
https://github.com/DataDog/chef-datadog/pull/186 Has been submitted, there's some progress there - but it's not ready for merge/release yet.

**Comment by miketheman** [comment]
Resolved via #296.

**Comment by chrissnell** [comment]
Did this ever get released?

**Comment by olivielpeau** [comment]
@chrissnell This got released with `v2.3.0` (see https://github.com/DataDog/chef-datadog/blob/v2.3.0/attributes/default.rb#L39-L45)
