### ISSUE TITLE
yum_package "datadog-agent" fails with a non-zero exit status

### ISSUE THREAD

**Issue by askmeaks** [DataDog/chef-datadog#175]
When I run the cookbook on Amazon Linux, it fails at installing the datadog-agent package and reports that it got a non-zero exit status. The log excerpt from chef-run is:
```text
Recipe: datadog::dd-agent

 * yum_package[datadog-agent-base] action remove (up to date)

 * yum_package[datadog-agent] action install

 ================================================================================
 Error executing action `install` on resource 'yum_package[datadog-agent]'
 ================================================================================

 Chef::Exceptions::Exec
 ----------------------
 returned 1, expected 0

 Resource Declaration:
 ---------------------
 # In /tmp/packer-chef-solo/cookbooks-0/datadog/recipes/dd-agent.rb

 39:   package 'datadog-agent' do
 40:     version dd_agent_version
 41:   end
 42: end

 Compiled Resource:
 ------------------
 # Declared in /tmp/packer-chef-solo/cookbooks-0/datadog/recipes/dd-agent.rb:39:in `from_file'

 yum_package("datadog-agent") do
 action :install
 retries 0
 retry_delay 2
 default_guard_interpreter :default
 package_name "datadog-agent"
 version "5.1.1-546"
 timeout 900
 flush_cache {:before=>false, :after=>false}
 declared_type :package
 cookbook_name :datadog
 recipe_name "dd-agent"
 end


 Running handlers:
 [2015-01-15T09:37:51+00:00] ERROR: Running exception handlers

 - Chef::Handler::Datadog
 Running handlers complete
 [2015-01-15T09:37:52+00:00] ERROR: Exception handlers complete
 [2015-01-15T09:37:52+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
 Chef Client failed. 73 resources updated in 120.502472096 seconds
 [2015-01-15T09:37:52+00:00] ERROR: yum_package[datadog-agent] (datadog::dd-agent line 39) had an error: Chef::Exceptions::Exec:  returned 1, expected 0
 [2015-01-15T09:37:52+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```
But when I try to install the package manually it exits with a non-zero status (but it does complain about a few issues in post-script section of the RPM package), excerpt below:
```text
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
grep: /etc/supervisord.conf: No such file or directory
  Installing : 1:datadog-agent-5.1.1-546.x86_64                                                                                             1/1 
Stopping Datadog Agent (using killproc on supervisord): [FAILED]
/etc/dd-agent/datadog.conf not found. Exiting.
Stopping Datadog Agent (using killproc on supervisord): [FAILED]
/etc/dd-agent/datadog.conf not found. Exiting.
  Verifying  : 1:datadog-agent-5.1.1-546.x86_64                                                                                             1/1 

Installed:
  datadog-agent.x86_64 1:5.1.1-546                                                                                                              

Complete!
$ echo $?
0
```

**Comment by miketheman** [comment]
Hi @askmeaks,

Can you provide the stacktrace referenced in the error message? I can't see from this message what exactly the failure is. `/var/chef/cache/chef-stacktrace.out`

**Comment by askmeaks** [comment]
Hi @miketheman,
The contents of the stacktrace is below:
```text
Generated at 2015-01-21 06:15:57 +0000
Chef::Exceptions::Exec: yum_package[datadog-agent] (datadog::dd-agent line 39) had an error: Chef::Exceptions::Exec:  returned 1, expected 0
/opt/chef/embedded/apps/chef/lib/chef/mixin/command.rb:158:in `handle_command_failures'
/opt/chef/embedded/apps/chef/lib/chef/provider/package/yum.rb:1021:in `yum_command'
/opt/chef/embedded/apps/chef/lib/chef/provider/package/yum.rb:1136:in `install_package'
/opt/chef/embedded/apps/chef/lib/chef/provider/package.rb:82:in `block in action_install'
/opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `call'
/opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:180:in `converge_by'
/opt/chef/embedded/apps/chef/lib/chef/provider/package.rb:80:in `action_install'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:582:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:315:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:400:in `block in run'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:399:in `catch'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:399:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:261:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:215:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:201:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:245:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:234:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:234:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:224:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:58:in `run'
/opt/chef/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:40:in `load'
/usr/bin/chef-solo:40:in `<main>'
```

**Comment by miketheman** [comment]
Hi @askmeaks,
Thanks for the stack - I guess I was hoping for the actual `yum` execution and error message. Could you try running Chef in debug logging mode - `-ldebug` - and see if you can capture the yum command and error message?

**Comment by askmeaks** [comment]
Hi @miketheman,
From the logs in the debug mode, it seems like that PREIN scriptlet is failing for the Datadog's rpm package.
The stacktrace is available at http://fpaste.org/172886/42191319/ and the excerpt from the chef-solo run in debug mode is available at http://fpaste.org/172887/19132761/

**Comment by miketheman** [comment]
Hi @askmeaks,
This is awesome, thanks! It definitely points to some sort of issue with the dd-agent installation, which is not particular to Chef.
Here's the code this script is invoking: https://github.com/DataDog/dd-agent-omnibus/blob/master/package-scripts/datadog-agent/preinst#L33-L54
Something in that block is likely failing, causing the Chef run to fail.

For reference, it appears that this happens on:
- Amazon Linux (version?)
- Upgrading from datadog-agent 4.4.0-88 to 5.1.1-546
- With the yum command: `yum -d0 -e0 -y install datadog-agent-5.1.1-546`

/cc: @remh

**Comment by askmeaks** [comment]
Hi @miketheman:
The version of Amazon Linux is "2014.9" and the base image does not have datadog-agent installed.

**Comment by askmeaks** [comment]
@miketheman and @remh,

I finally found the culprit and fixed the issue. The PREIN script looks for **/etc/issue** file to determine the distribution, see excerpt below:
```bash
 LINUX_DISTRIBUTION=$(grep -Eo "(Debian|Ubuntu|RedHat|CentOS|openSUSE|Amazon)" /etc/issue)
```
Where in on my machine, the file was overwritten with a custom content and hence the installation was failing with error message saying that the system is not supported:
```text
---- Begin output of  ----
STDOUT: [ FAILED ]\tYour system is currently not supported by this script.
error: %pre(datadog-agent-1:5.1.1-546.x86_64) scriptlet failed, exit status 1STDERR: Error in PREIN scriptlet in rpm package 1:datadog-agent-5.1.1-546.x86_64
---- End output of  ----
```
When I added a line with text "Amazon" at the end of the file, I was finally able to install datadog-agent.

Thanks for all the help.

**Comment by alq666** [comment]
@remh `lsb_release -d` is a better way to determine the distribution.

**Comment by miketheman** [comment]
@alq666 @remh not all distros include lsb tools in the base, that's why tools like ohai/gohai/etc use a few methods to try to determine the distro.
Agreed that lsb_release is likely to be a better first test, and if failed, try another method.

But in any case, that's an issue for the dd-agent-omnibus repo.

@askmeaks glad we could help!

**Comment by jyotijazz** [comment]
Could someone help me in resolving the error below which I am getting while chef is trying to install datadog agent on AWS Ubuntu host.

10.10.12.238 [2022-05-11T15:48:44+00:00] FATAL: Chef::Exceptions::Package: apt_package[datadog-agent] (datadog::_install-linux line 34) had an error: Chef::Exceptions::Package: No candidate version available for datadog-agent
==========================================================

10.10.12.238   * apt_repository[datadog-beta] action remove (up to date)
10.10.12.238 Recipe: datadog::_install-linux
10.10.12.238   * apt_package[datadog-agent] action install
10.10.12.238     * No candidate version available for datadog-agent
10.10.12.238     ================================================================================
10.10.12.238     Error executing action `install` on resource 'apt_package[datadog-agent]'
10.10.12.238     ================================================================================
10.10.12.238
10.10.12.238     Chef::Exceptions::Package
10.10.12.238     -------------------------
10.10.12.238     No candidate version available for datadog-agent
10.10.12.238
10.10.12.238     Resource Declaration:
10.10.12.238     ---------------------
10.10.12.238     # In /var/chef/cache/cookbooks/datadog/recipes/_install-linux.rb
10.10.12.238
10.10.12.238      34:   apt_package dd_agent_flavor do
10.10.12.238      35:     version dd_agent_version
10.10.12.238      36:     retries package_retries unless package_retries.nil?
10.10.12.238      37:     retry_delay package_retry_delay unless package_retry_delay.nil?
10.10.12.238      38:     action package_action # default is :install
10.10.12.238      39:     options '--force-yes' if node['datadog']['agent_allow_downgrade']
10.10.12.238      40:   end
10.10.12.238      41: when 'rhel', 'fedora', 'amazon'
10.10.12.238
10.10.12.238     Compiled Resource:
10.10.12.238     ------------------
10.10.12.238     # Declared in /var/chef/cache/cookbooks/datadog/recipes/_install-linux.rb:34:in `from_file'
10.10.12.238
10.10.12.238     apt_package("datadog-agent") do
10.10.12.238       package_name "datadog-agent"
10.10.12.238       action [:install]
10.10.12.238       default_guard_interpreter :default
10.10.12.238       declared_type :apt_package
10.10.12.238       cookbook_name "datadog"
10.10.12.238       recipe_name "_install-linux"
10.10.12.238       version nil
10.10.12.238     end
