### ISSUE TITLE
Chef 12 throws warnings for compile_time resources

### ISSUE THREAD

**Issue by wickett** [DataDog/chef-datadog#189]
With Chef 12 these warnings now show up for the chef-datadog cookbook.

```
[2015-03-24T15:38:02+00:00] WARN: chef_gem[chef-handler-datadog] chef_gem compile_time installation is deprecated
[2015-03-24T15:38:02+00:00] WARN: chef_gem[chef-handler-datadog] Please set `compile_time false` on the resource to use the new behavior.
[2015-03-24T15:38:02+00:00] WARN: chef_gem[chef-handler-datadog] or set `compile_time true` on the resource if compile_time behavior is required.
```

As noted by @jtimberman these can be fixed by adding this line to the resource for maximum backward compatibility.

```
 compile_time true if Chef::Resource::ChefGem.instance_methods(false).include?(:compile_time)
```

See http://jtimberman.housepub.org/blog/2015/03/20/chef-gem-compile-time-compatibility/

**Comment by wickett** [comment]
Any update on this?

**Comment by alq666** [comment]
@wickett thanks for filing the issue.

@miketheman any thoughts on this?

**Comment by miketheman** [comment]
Thanks for reporting this. There's been an ongoing thread on the Chef mailing lists on the behavior of `compile_time` and Chef 12. 
Yesterday, a post-mortem was produced: https://gist.github.com/thommay/42b033d2c877e74e6b1a

Chef have also publicly apologized for introducing the WARN spam here: https://www.chef.io/blog/2015/02/17/chef-12-1-0-chef_gem-resource-warnings/

Before changing the behavior, we would likely need to test whether or not we should be running at compile_time any more.
