### ISSUE TITLE
Synchronize with current dd-agent configuration examples (Numero Dos)

### ISSUE THREAD

**Issue by miketheman** [DataDog/chef-datadog#194]
Following #154, continue with sync for another milestone.
- [ ] hdfs
- [ ] iis
- [ ] jenkins
- [ ] kafka_consumer
- [ ] kyototycoon
- [ ] lighttpd
- [ ] memcache
- [ ] mongo
- [ ] mysql
- [ ] network
- [ ] nginx
- [x] postgres (also see #140)
- [ ] rabbitmq
- [ ] redisdb
- [ ] riak
- [ ] tomcat
- [x] varnish
- [ ] zookeeper

**Comment by mcg** [comment]
Any chance this is still being worked on? Trying to use the Nginx module and it's out of date, doesn't support "ssl_validation".

**Comment by iancward** [comment]
@mcg in case you didn't see #194, the `ssl_validation` option is now supported for the nginx integration.
