### ISSUE TITLE
The jmx configuration from the latest template does not match dd-agent 5.3.0+

### ISSUE THREAD

**Issue by brentryan** [DataDog/chef-datadog#202]
We noticed recently that this most recent version creates a jmx.yaml file with an attribute called "server" instead of "host" which is expected by the jmx integration.

Can this be fixed?

**Comment by miketheman** [comment]
@brentryan The JMX template renders any attributes passed in. See here: https://github.com/DataDog/chef-datadog/blob/master/templates/default/jmx.yaml.erb

So somewhere in your attributes settings, you are passing `server` instead of `host`. See https://github.com/DataDog/chef-datadog/blob/master/recipes/jmx.rb#L8 for an example.

**Comment by brentryan** [comment]
So the old template used to do this:

    host: <%= i["server"] %>

And we passed in an attribute called "server" to match this.

In the new template it just uses what we pass in so this cookbook changes breaks backward compatibility.

I actually think the change is probably a good change, but maybe this should have been a major revision number change of the cookbook to indicate that it's a breaking change then.

Thoughts?

**Comment by miketheman** [comment]
@brentryan I agree that this was a potentially breaking change.

However, since we never actually documented the correct behavior, rather had bulk-shipped a bunch of templates without setting them up properly, we felt that this wasn't enough to bump the revision.

A bit from the changelog:

> NOTE This has been broken for some time, and has had multiple attempts at fixing properly. The correct interface has never been documented, and the implementation has always been left up to the reader. We have changed this to be much simpler - instead of trying to account for any possible methods.
