### ISSUE TITLE
Berkshelf installs old version of chef-datadog

### ISSUE THREAD

**Issue by awasilyev** [DataDog/chef-datadog#213]
While contributing cookbooks with berks, datadog-0.1.2 installed by default instead of latest version

**Comment by rmoriz** [comment]
have the same issue…

**Comment by miketheman** [comment]
I don't think I understand - can you provide a more complete example, and some debugging? A gist with the output of your Berksfile, Berksfile.lock and `berks install -d` ?

**Comment by rmoriz** [comment]
when no explicit version is given, Berkshelf installes 0.1.2 instead of the latest version available. This might have been fixed with https://github.com/berkshelf/berkshelf/blob/master/CHANGELOG.md#324

**Comment by awasilyev** [comment]
Oh, thank you

**Comment by miketheman** [comment]
Closing, as this is a berks issue, not this cookbook's.
