### ISSUE TITLE
Allow passing a custom hostname to chef-handler-datadog

### ISSUE THREAD

**Issue by olivielpeau** [DataDog/chef-datadog#226]
Was discussed here https://github.com/DataDog/chef-handler-datadog/issues/41#issuecomment-41585416

It would be useful to find a sensible way to pass a custom hostname to the handler while preserving the priority of the ec2 flag. Opening this issue because a customer is not on ec2 and may need this feature.

**Comment by miketheman** [comment]
This would likely live in https://github.com/DataDog/chef-datadog/blob/master/recipes/dd-handler.rb#L34-L38

**Comment by olivielpeau** [comment]
Fixed with #308. Closing
