### ISSUE TITLE
Chef recipe folder name must match the metadata name

### ISSUE THREAD

**Issue by DBLaw** [DataDog/chef-datadog#269]
As reported by a customer:

>The chef-datadog recipe no longer works out of the box. Chef made a breaking change so that the recipe folder name must match the metadata name “datadog”. Simple fix to re-name the recipe to “datadog" but might want to have that step put on the website.

**Comment by miketheman** [comment]
I don't think I fully understand the user's scenario.

Typically, users should be pulling the cookbook from the [Supermarket](https://supermarket.chef.io/cookbooks/datadog), not directly from GitHub.
This is where released versions live.
Alternately, the cookbook can be downloaded from the [Releases page](https://github.com/DataDog/chef-datadog/releases).

When using a cookbook manager like Berkshelf, and still wanting to retrieve the cookbook from GitHub, the correct syntax would look something like this:

```ruby
cookbook 'datadog', github: 'DataDog/chef-datadog', tag: 'v2.2.0'
```

More details on Berksfile syntax can be found at http://berkshelf.com/
