### ISSUE TITLE
Datadog_monitor LWRP error

### ISSUE THREAD

**Issue by rohit-conn** [DataDog/chef-datadog#282]
Hello,

We have custom recipe which uses the datadog custom resource datadog_monitor in our own cookbook datadog-agent

http://pastebin.com/cK0HMyUi

This used to work with the previous version which is 2.1 but is throwing an error that the template is missing., eventhough we have a template in the template/default directory of our cookbook datadog-agent
Can you please let me know what modification we have to make for this to work again.
Currently we are using chef-client 12.6

**Comment by miketheman** [comment]
Hi @rohit-conn !

Sorry for the problem. It appears that the change in https://github.com/DataDog/chef-datadog/pull/212 is what is affecting you. This was also reported similarly in https://github.com/DataDog/chef-datadog/issues/230.

The simplest fix is to add the cookbook's name to the resource, something like this:

```ruby
datadog_monitor 'php_fpm' do
  cookbook 'datadog-agent'
  instances node['datadog']['php-fpm']['instances']
end
```

This should inform the resource to look in the `datadog-agent` cookbook's template/ directory for the associated template.

**Comment by rohit-conn** [comment]
Hello @miketheman,

Thanks, the fix is working.
