### ISSUE TITLE
Agent with Postfix check gets "conversation failed" from sudoing

### ISSUE THREAD

**Issue by iiro** [DataDog/chef-datadog#287]
Hi,

I'm using your Postfix check with Chef - and keep getting this into my logs:

```
Mar 21 21:47:27 tk-policy-mn-gitlab-ubuntu-14-04-021010 sudo: dd-agent : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=list
Mar 21 21:47:27 tk-policy-mn-gitlab-ubuntu-14-04-021010 sudo: dd-agent : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/find /var/spool/postfix/incoming -type f
Mar 21 21:47:27 tk-policy-mn-gitlab-ubuntu-14-04-021010 sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 21 21:47:27 tk-policy-mn-gitlab-ubuntu-14-04-021010 sudo: pam_unix(sudo:session): session closed for user root
Mar 21 21:47:27 tk-policy-mn-gitlab-ubuntu-14-04-021010 sudo: dd-agent : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=list
Mar 21 21:47:27 tk-policy-mn-gitlab-ubuntu-14-04-021010 sudo: dd-agent : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/find /var/spool/postfix/active -type f
Mar 21 21:47:27 tk-policy-mn-gitlab-ubuntu-14-04-021010 sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 21 21:47:27 tk-policy-mn-gitlab-ubuntu-14-04-021010 sudo: pam_unix(sudo:session): session closed for user root
Mar 21 21:47:27 tk-policy-mn-gitlab-ubuntu-14-04-021010 sudo: dd-agent : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=list
Mar 21 21:47:27 tk-policy-mn-gitlab-ubuntu-14-04-021010 sudo: dd-agent : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/find /var/spool/postfix/deferred -type f
Mar 21 21:47:27 tk-policy-mn-gitlab-ubuntu-14-04-021010 sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
```
## 

I have these in my Policyfile:

```
default['authorization']['sudo']['passwordless'] = true
default['authorization']['sudo']['include_sudoers_d'] = true
default['datadog']['api_key'] = 'xxxxxxx'
default['datadog']['application_key'] = 'yyyyyy'

default['datadog']['postfix']['instances'] = [
  {
    'directory' => '/var/spool/postfix',
    'queues' => ['incoming', 'active', 'deferred'],
    'tags' => ['gitlab']
  }
]
```

and my run list has:
run_list(
  'apt::default',
  'sudo::default',
  'ntp::default',
  'papertrail::default',
  'postfix::default',
  'omnibus-gitlab::default',
  'omnibus-gitlab::backup_cron_job',
  'datadog::dd-handler',
  'datadog::dd-agent',
  'datadog::postfix',
  'datadog::nginx',
  'datadog::postgres',
  'datadog::redisdb'
)

Interestingly - dd-agent seems to be happy - and so does the DD web UI:

```
root@tk-policy-mn-gitlab-ubuntu-14-04-021010:~# dd-agent check postfix
2016-03-21 20:06:57,664 | WARNING | dd.collector | checks.disk(disk.py:74) | Using `use_mount` in datadog.conf has been deprecated in favor of `use_mount` in disk.yaml
2016-03-21 20:06:57,665 | INFO | dd.collector | config(config.py:899) | initialized checks.d checks: ['postgres', 'postfix', 'ntp', 'nginx', 'redisdb', 'disk', 'network']
2016-03-21 20:06:57,665 | INFO | dd.collector | config(config.py:900) | initialization failed checks.d checks: []
2016-03-21 20:06:57,665 | INFO | dd.collector | checks.collector(collector.py:533) | Running check postfix
Metrics:
[('postfix.queue.size',
  1458590817,
  0,
  {'hostname': 'policy-mn-gitlab-ubuntu-14-04',
   'tags': ['gitlab', 'queue:active', 'instance:postfix'],
   'type': 'gauge'}),
 ('postfix.queue.size',
  1458590817,
  0,
  {'hostname': 'policy-mn-gitlab-ubuntu-14-04',
   'tags': ['gitlab', 'queue:deferred', 'instance:postfix'],
   'type': 'gauge'}),
 ('postfix.queue.size',
  1458590817,
  0,
  {'hostname': 'policy-mn-gitlab-ubuntu-14-04',
   'tags': ['gitlab', 'queue:incoming', 'instance:postfix'],
   'type': 'gauge'})]
Events:
[]
Service Checks:
[]
Service Metadata:
[{}]
    postfix
    -------
      - instance #0 [OK]
      - Collected 3 metrics, 0 events & 0 service checks


```

Ideas? OS is Ubuntu 14.04 LTS.

Apparently this is just a logging (pollution) issue...

**Comment by iiro** [comment]
...or it's not reporting correctly. I have this issue also on two production Ubuntu's (running 12.04 LTS and 14.04 LTS).

**Comment by miketheman** [comment]
@iiro that's a good question - the postfix integration needs to be able to run as sudo and execute `find` commands.

If you wanted to suppress sudo logging for this kind of message, you could probably [manipulate the sudo config](http://stackoverflow.com/a/14278264/244037), but that's definitely beyond the scope of this cookbook.

If there's an issue with collection/reporting, then that should be opened against the [dd-agent](https://github.com/DataDog/dd-agent) repo.

**Comment by iiro** [comment]
Summarizing everything I know: actually the sudo logging itself is not the issue after all. The issue is that chef-datadog cookbook does configure incorrect permissions (dd-agent info shows that everything is ok but you get a zero value to the queue metric).

The correct sudoers(.d) line seems to be the one in the example YAML file in here: https://github.com/DataDog/dd-agent/blob/master/conf.d/postfix.yaml.example

When I modify the Chef-managed version to the same as in example YAML - the metric works and a correct value is submitted to DD.

**Comment by miketheman** [comment]
@iiro can you help us out here and show what a correct sudoers line looks like? Please redact any sensitive information, of course.

**Comment by iiro** [comment]
@miketheman sure. Sorry about the misleadings...

The working one uncommented here - the Chef-configured (non-working one) commented out.
```
# cat /etc/sudoers.d/dd-agent-find-postfix
# This file is managed by Chef.
# Do NOT modify this file directly.

dd-agent ALL=(ALL) NOPASSWD:/usr/bin/find
# dd-agent ALL=(ALL) NOPASSWD:/usr/bin/find /var/spool/postfix
```

If I comment out the first one and uncomment the other - and wait for 30-40 seconds - I can see that the metric in DD UI goes back to zero (assuming I have messages in queue). And vice versa. :) Very repeatable :)

**Comment by miketheman** [comment]
I _think_ I see the problem here.

With sudoers, if we supply the config:

     dd-agent ALL=(ALL) NOPASSWD:/usr/bin/find

then any argument passed to `find` is allowed - so it's possible that the dd-agent user _could_ be used to run `find` against some other restriced directory.

This is why the config of:

    dd-agent ALL=(ALL) NOPASSWD:/usr/bin/find /var/spool/postfix

is meant to only allow something like `sudo /usr/bin/find /var/spool/postfix` and it appears that the command is attempting to run the equivalent of `sudo /usr/bin/find /var/spool/postfix/<queuename>` instead.

The [logic here](https://github.com/DataDog/chef-datadog/blob/dae90fcd9e96f5373fe48615c40d15f5460c991c/recipes/postfix.rb#L28-L31) is what sets up this command.

I wonder if @phlipper , the original author of the postfix chef code could weigh in here?

**Comment by iiro** [comment]
Can this be a general and common issue? I guess it could - as you get "ok" (returns always 0) - so this could be affecting some amount of users...

**Comment by BrentOnRails** [comment]
Having the same issue. 

I either have to override the command to be /usr/bin/find only or map the commands with the queues i want.

`  dd_sudo = resources("sudo[dd-agent-find-postfix]")
  dd_sudo.commands = ["/usr/bin/find"]
  dd_sudo.run_action(:install)
`

The datadog postfix plugin installation docs specify to allow /usr/bin/find in the sudoers file, however you also have the option of mapping the queues into commands as well (which is probably what the cookbook should do for those who don't want the agent able to use find everywhere)

`  postfix_instances = Array(node['datadog']['postfix']['instances'])
  postfix_commands = postfix_instances.map do |instance|
    instance['queues'].map do |queue|
      "/usr/bin/find #{instance['directory']}/#{queue} -type f"
    end
  end

  dd_sudo = resources("sudo[dd-agent-find-postfix]")
  dd_sudo.commands = postfix_commands.flatten.uniq
  dd_sudo.run_action(:install)
`

**Comment by BrentOnRails** [comment]
https://github.com/DataDog/chef-datadog/pull/305
