### ISSUE TITLE
Unable to run integrations

### ISSUE THREAD

**Issue by clarter** [DataDog/chef-datadog#288]
I've tried with both varnish and apache and get similar issues. I'm willing to bet this is user error, I'm just not sure exactly why they are failing. The dd-0agent is installed via Chef and running, but when adding datadog:apache to the run list I get the following:

```
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/datadog/recipes/apache.rb
================================================================================


NoMethodError
-------------
undefined method `[]' for nil:NilClass


Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/datadog/recipes/apache.rb:21:in `from_file'
  /var/chef/cache/cookbooks/datadog/recipes/apache.rb:20:in `from_file'


Relevant File Content:
----------------------
/var/chef/cache/cookbooks/datadog/recipes/apache.rb:

 14:  #   {
 15:  #     'status_url' => "http://localhost:82/status/",
 16:  #     'name' => ["test"]
 17:  #   }
 18:  # ]
 19:
 20:  datadog_monitor 'apache' do
 21>>   instances node['datadog']['apache']['instances']
 22:  end
 23:



Running handlers:
Running handlers complete

Chef Client failed. 0 resources updated in 10.388931 seconds
```

**Comment by miketheman** [comment]
Hi @clarter !

This cookbook requires a bit more configuration that dropping in a recipe to the run list, as expressed in each recipe's internal documentation.

Here's the notes from the apache recipe: https://github.com/DataDog/chef-datadog/blob/master/recipes/apache.rb#L3-L18

So you typically assign these details in a role, wrapper cookbook, etc to be made available during the recipe's run, where it inspects the `node['datadog']['apache']['instances']` namespace, where it is currently erroring on not having anything there.

Let us know if this helps!

**Comment by clarter** [comment]
Thanks, got it figured out.

**Comment by miketheman** [comment]
Great news!
