### ISSUE TITLE
API Key set in attribute and stored on Chef Server

### ISSUE THREAD

**Issue by hartfordfive** [DataDog/chef-datadog#292]
Currently, to specify the API key, you need to set it as a node attribute.  For example, fetching the API key from an encrypted databag:

```ruby
creds = Chef::EncryptedDataBagItem.load('datadog', 'creds')
node.default['datadog']['api_key'] = creds['api_key']
node.default['datadog']['application_key'] = creds['application_key']

include_recipe 'datadog::dd-agent'
include_recipe 'datadog::dd-handler'
```

The property ends up being in clear-text in your chef server.  For some this might be OK, but i'm sure in many cases, some would prefer to not have this value stored in the node attributes on the chef server. Could an additional property be created which would allow you to set the run_state variable the value could be obtained from?  For example:
```ruby
node.default['datadog']['api_key_runstate_var'] = 'datadog_api_key'
```
would force the data dog recipe to fetch the API key from `node.run_state['datadog_api_key']` variable, thus preventing the value form being stored in the node attributes.

**Comment by hartfordfive** [comment]
I've created a [PR](https://github.com/DataDog/chef-datadog/pull/293) for this.

**Comment by miketheman** [comment]
I added a comment on the PR with a viable workaround: https://github.com/DataDog/chef-datadog/pull/293#issuecomment-213088218

**Comment by miketheman** [comment]
Closing based on https://github.com/DataDog/chef-datadog/pull/293#issuecomment-214337405
