### ISSUE TITLE
yum gpg key should be an attribute

### ISSUE THREAD

**Issue by icberg7** [DataDog/chef-datadog#311]
Our servers are behind a firewall, and we use a proxy/mirror to make the RPM packages available internally. We also need to host the GPG keys internally somewhere as well, so we really need to be able to configure the gpg key through a wrapper or something.

**Comment by olivielpeau** [comment]
Hi @icberg7, such a feature would be very welcome, would you mind opening a PR implementing it? (as you seem to have implemented it on your fork of the cookbook)

Thanks!

**Comment by iancward** [comment]
Hi @olivielpeau I had to get approval to submit, but now that it's approved, please see #326.

Thanks.
