### ISSUE TITLE
Use lazy evaluation for node attributes rendered into templates

### ISSUE THREAD

**Issue by mfischer-zd** [DataDog/chef-datadog#328]
Assume a user wants to store the API key in an external information service other than Chef server, such as Amazon S3 or Hashicorp Vault.  This key would be fetched during the run phase, not the compile phase; and therefore the attribute cannot be set during the compile phase as with other attributes.

So, use Chef's `lazy` (delayed evaluation) operator where possible in any resource attributes that render files.

**Comment by haidangwa** [comment]
`node['datadog']['tags']` are another good case for a bugfix of this nature
