### ISSUE TITLE
remove-dd-agent recipe is not Windows compatible

### ISSUE THREAD

**Issue by gzysk8** [DataDog/chef-datadog#331]
This came in via a support ticket:

I believe the `datadog::remove-dd-agen`t recipe is incorrect. I was testing it before I installed the software broadly for a trial. The issue is `action :purge`, as it is currently used in that recipe, only works on Linux (specifically, Ubuntu per the documentation). To make this work for Linux and Windows (thus far, tested on Windows 2012 R2 and CentOS 7), the following code worked:

```
case node['os']

when 'linux'

package 'datadog-agent' do

action :purge

end

when 'windows'

package 'Datadog Agent' do

action :remove

end

end
```

**Comment by olivielpeau** [comment]
That is correct, the `datadog::remove-dd-agent` hasn't been updated to support Windows yet. Thanks for the snippet, I'm adding the issue in Triage but we should probably take care of it for the minor release after next.
