### ISSUE TITLE
Create gunicorn recipe

### ISSUE THREAD

**Issue by mlcooper** [DataDog/chef-datadog#339]

**Comment by olivielpeau** [comment]
@mlcooper: Thanks for your contribution!

It looks like you have a commit ready on your fork, could you open a PR against this repository? This will allow us to review and merge your changes ;)

**Comment by mlcooper** [comment]
Hi @olivielpeau I'm just waiting for approval internally within my company for me to be able to open this PR.  Shouldn't be much longer.

**Comment by mlcooper** [comment]
@olivielpeau PR has been opened and it passed the CI tests.

**Comment by olivielpeau** [comment]
Resolved in #355, will be in next minor release. Closing. Thanks @mlcooper!
