### ISSUE TITLE
Do not install datadog-agent package if it is already installed

### ISSUE THREAD

**Issue by debashis1982** [DataDog/chef-datadog#352]
Hi,

Can we add a check here https://github.com/DataDog/chef-datadog/blob/master/recipes/_install-linux.rb#L41 to not install datadog-agent package if it is not installed already?
We want to speed up our wrapper cookbook run by running them on VMs created from images that already have datadog-agent package installed.

Thanks!

**Comment by olivielpeau** [comment]
Hi @debashis1982!

I'm not sure I understand, it's the `package` resource's responsibility to check whether the agent package is installed, and if the agent is already installed it shouldn't try to install it on the node. The check itself should be fairly quick and shouldn't slow down the chef run. What are you experiencing exactly?

**Comment by debashis1982** [comment]
@olivielpeau Thanks! I was actually looking at it wrongly. It is a non-issue. Closing.
