### ISSUE TITLE
opsworks howto?

### ISSUE THREAD

**Issue by sbagmeijer** [DataDog/chef-datadog#376]
we are both new to aws opswork/chef and to datadog we tried to follow the instructions to get the datadog client to install by chef on all our servers but we don't seems to fully understand all the steps required.

Is there someone with an example chef module that installs datadog so we can have a look how it is actually done? We are trying to install datadog from our own chef module.

**Comment by olivielpeau** [comment]
Hi @sbagmeijer, have you followed the instructions in the README? https://github.com/DataDog/chef-datadog#usage (especially step `4` which adds a role which `run_list` includes the `datadog::dd-agent` recipe)

Could you give use more info on what you've set up and what doesn't seem to work?

**Comment by olivielpeau** [comment]
Closing, let us know if you need more information @sbagmeijer
