### ISSUE TITLE
Tag / Cut new release

### ISSUE THREAD

**Issue by theckman** [DataDog/chef-datadog#378]
Looks like there have been some merges to master, including a bugfix/enhancement (`dd-agent` isn't added to the docker group). I can workaround this by pinning the cookbook to a git hash, but that's not ideal. Would you be willing to cut either a `2.6.1` or a `2.7.0` so I can remove the workaround?

Cheers!

**Comment by olivielpeau** [comment]
Hi @theckman, you're right there are a few changes that we haven't released yet, I'll work on getting `2.7.0` released by Monday, thanks for your patience

**Comment by theckman** [comment]
@olivielpeau I just found a pretty gnarly bug with the way the `postgres` template is rendered that I'm going to need to patch very soon. I'm being a bit selfish here, but could we delay `2.7.0` so that I can open an issue detailing the problem and open a PR with a proposed fix?

I'm hoping to get all of that done during the day on Sunday (PST). This would avoid me having to continue running a pinned cookbook until either a `2.7.1` or `2.8.0` is released.

**Comment by olivielpeau** [comment]
@theckman Sounds good! If you can open the PR by Monday I'll be happy to review it and include it in `2.7.0`

**Comment by theckman** [comment]
@olivielpeau this might be a bigger yak than I thought: #379.

**Comment by theckman** [comment]
@olivielpeau @miketheman helpfully opened #380 which fixes the issue I was hoping we could get in for the `2.7.0` release. With it including breaking changes I'm not sure how possible that is.

**Comment by miketheman** [comment]
To be clear, the PR I opened has 0 breaking changes. Removing the
customized template logic is the breaking changes for the next major
revision.

**Comment by theckman** [comment]
Oops! That was my bad, I missed it with how GitHub generated the diff:

* https://github.com/DataDog/chef-datadog/pull/380/files#diff-2f0a7ed4dff39b27e80825e1aa90f6faR12

Sorry about that.

**Comment by olivielpeau** [comment]
`2.7.0` is out, closing

Thanks @theckman and @miketheman!

**Comment by theckman** [comment]
@olivielpeau you da realest MVP.
