### ISSUE TITLE
Duplicate installation of apt-transport-https package / resource cloning / chef13

### ISSUE THREAD

**Issue by rmoriz** [DataDog/chef-datadog#392]
Hi,

https://github.com/DataDog/chef-datadog/blob/2a7e914993f76f452e09268dae9c2d69f1a7fe13/recipes/repository.rb#L24-L26 does a resource clone as the package resource is already defined in the apt cookbook at https://github.com/chef-cookbooks/apt/blob/7d6310eee239072b6b013f5b6f2c4f10a01c3f0b/recipes/default.rb#L85

```shell
       [2017-01-19T12:26:49+00:00] ERROR: Cloning resource attributes for apt_package[apt-transport-https] from prior resource
       Previous apt_package[apt-transport-https]: /tmp/kitchen/cache/cookbooks/apt/recipes/default.rb:85:in `from_file'
       Current  apt_package[apt-transport-https]: /tmp/kitchen/cache/cookbooks/datadog/recipes/repository.rb:24:in `from_file' (CHEF-3694)/tmp/kitchen/cache/cookbooks/datadog/recipes/repository.rb:24:in `from_file'.
       Please see https://docs.chef.io/deprecations_resource_cloning.html for further details and information on how to correct this problem. at /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/formatters/doc.rb:419:in `deprecation'
```

This affects users who already prepare their chef setup for chef13 and enable "deprecations_as_errors" in their kitchen setups.

**Comment by olivielpeau** [comment]
Thanks @rmoriz for the feedback and PR, there's a discussion about this issue in #388.

Basically removing this resource from the `datadog` cookbook would require bumping the dependency on the `apt` cookbook. Instead we could change the name of the resource in this cookbook to avoid resource cloning (see the PR I linked to for the full discussion, feel free to respond there)

**Comment by bai** [comment]
I think this could be closed as https://github.com/DataDog/chef-datadog/pull/388 has been merged 👍 

P.S. @rmoriz Can't help but say thanks for your work on `hetzner-api`!
