### ISSUE TITLE
remote_file[DATADOG_RPM_KEY_E09422B3.public] needs a guard if the key is already cached or already imported

### ISSUE THREAD

**Issue by haidangwa** [DataDog/chef-datadog#403]
https://github.com/DataDog/chef-datadog/blob/master/recipes/repository.rb#L56-L59 needs a guard. This resource is executed on every chef run even if the key has already been cached. The problem is not only downloading unnecessarily on every chef run, but the real issue comes into play when the remote source URL becomes unavailable. For example, if a node's remote RPM repo goes offline and the key can't be downloaded, it will cause the entire chef run to fail. Since the key is cached on the node already, this instance should not fail a chef run. Doubly so if the rpm gpg key has already been imported.

Chef run failure:
```
13T02:33:27+00:00] ERROR: remote_file[DATADOG_RPM_KEY_E09422B3.public] (datadog::repository line 56) had an error: Errno::ECONNRESET: Error connecting to https://******.com/nexus/content/repositories/Chef-Master/com/datadog/datadog_rpm_key.public/E09422B3/datadog_rpm_key.public-E09422B3.public - Connection reset by peer
```

Above key is already cached:
```
# ls -l /var/chef/cache/DATADOG_RPM_KEY_E09422B3.public 
-rw-r--r-- 1 root root 1662 Nov 23 18:12 /var/chef/cache/DATADOG_RPM_KEY_E09422B3.public
```

**Comment by iancward** [comment]
It looks like the `execute` resource that handles the actual import is guarded (https://github.com/DataDog/chef-datadog/blob/master/recipes/repository.rb#L65), so this guard could be added to the `remote_file` resource; also, one could be configured to notify the other.
