### ISSUE TITLE
chef-handler-datadog gem cannot be installed on restricted networks

### ISSUE THREAD

**Issue by dsalvador-dsalvador** [DataDog/chef-datadog#408]
Servers in restricted networks cannot reach https://rubygems.org to download the chef-handler-datadog gem.

I have created PR https://github.com/DataDog/chef-datadog/pull/407, which accounts for an optional attribute which the user can set to specify a custom gem server.  If the attribute is not set, then the default server https://rubygems.org will remain in use.

Here's an example of setting the attribute in the PR in some other cookbook that requires chef-datadog.
`default['datadog']['gem_server'] = 'http://custom.gem_server.org'`

**Comment by olivielpeau** [comment]
Fixed in #413
