### ISSUE TITLE
enable_trace_agent Attribute Breaks Configuration for Service Discovery

### ISSUE THREAD

**Issue by bflad** [DataDog/chef-datadog#418]
Hello there!

We tried switching our attributes from:
```ruby
default['datadog']['extra_config'] = {
    'apm_enabled' => 'true',
    'service_discovery_backend' => 'docker',
    'sd_config_backend' => 'consul',
    'sd_backend_host' => '127.0.0.1',
    'sd_backend_port' => '8500'
}
```

To the new `enable_trace_agent` attribute via:

```ruby
default['datadog']['enable_trace_agent'] = true 
default['datadog']['extra_config'] = {
    'service_discovery_backend' => 'docker',
    'sd_config_backend' => 'consul',
    'sd_backend_host' => '127.0.0.1',
    'sd_backend_port' => '8500'
}
```

However in the configuration template for `enable_trace_agent` (https://github.com/DataDog/chef-datadog/blob/master/templates/default/datadog.conf.erb#L64-L75), it inserts new subsection headers into the configuration file, which breaks service discovery by not switching the configuration subsection back to `[Main]`:

```python
# Generated by Chef, local modifications will be overwritten

[Main]
...
## Trace settings
apm_enabled: true

[trace.sampler]
extra_sample_rate: 1
max_traces_per_second: 10

[trace.receiver]
receiver_port: 8126
connection_limit: 2000
...
# ========================================================================== #
# Other config options
# ========================================================================== #
service_discovery_backend: docker
sd_config_backend: consul
sd_backend_host: 127.0.0.1
sd_backend_port: 8500
```

The most simple fix would be to add a `[Main]` line at the end of the if statement in the template. However it would be also nice if service discovery had proper attributes that would be placed above the trace agent config.

**Comment by olivielpeau** [comment]
I'll go ahead and close this since you fixed the issue on the trace agent config option @bflad, thanks again!

The changes on the service discovery attributes will be released with the next minor
