### ISSUE TITLE
Documentation link in recipes/docker.rb is a 404

### ISSUE THREAD

**Issue by cmessinaclearchannel** [DataDog/chef-datadog#421]
https://github.com/DataDog/chef-datadog/blob/master/recipes/docker.rb#L22
refers to https://www.datadoghq.com/2014/06/monitor-docker-datadog/
This page does not exist.

Also at https://github.com/DataDog/chef-datadog/blob/master/recipes/docker_daemon.rb#L22

**Comment by olivielpeau** [comment]
Thanks @cmessinaclearchannel for reporting this! I think we should update these comments so that they refer to http://docs.datadoghq.com/integrations/docker/

Feel free to open a PR addressing this, otherwise we'll do it for the next release
