### ISSUE TITLE
dd-handler broken in chef-client 13

### ISSUE THREAD

**Issue by AlexBevan** [DataDog/chef-datadog#426]
include_recipe 'datadog::dd-handler'

================================================================================
  Recipe Compile Error in /var/chef/cache/cookbooks/zone_Xenial_base/recipes/default.rb
  ================================================================================

  NoMethodError
  -------------
  chef_handler[Chef::Handler::Datadog] (datadog::dd-handler line 52) had an error: NoMethodError: undefined method `new' for ChefHandler:Module

**Comment by olivielpeau** [comment]
Hi @AlexBevan, thanks for reporting this!

This issue seems to come from the `chef_handler` cookbook: https://github.com/chef-cookbooks/chef_handler/issues/50
Could you try using the latest version of `chef_handler` (`2.1.1`) and see if you're still experiencing this issue? Thanks!

**Comment by AlexBevan** [comment]
Right you are, thanks for the swift reply!
