### ISSUE TITLE
http_check template does not allow to provide init_config

### ISSUE THREAD

**Issue by rmoriz** [DataDog/chef-datadog#442]
file https://github.com/DataDog/chef-datadog/blob/master/templates/default/http_check.yaml.erb

no way to set
```
init_config:
  skip_event: true
```

related https://github.com/DataDog/dd-agent/issues/1128

should be a default IMHO

**Comment by mlcooper** [comment]
I use the `skip_event: true` setting, but under the `instances` section of the `http_check.yaml` config file, and it works fine, as shown in their master http_check example file (it being in the `instances` section):

https://github.com/DataDog/integrations-core/blob/master/http_check/conf.yaml.example#L114

**Comment by aioue** [comment]
confirming this doesn't remove the deprecation message on `5.20.0`

```
init_config:
  skip_event: True
```

**Comment by olivielpeau** [comment]
Thanks for providing the workaround @mlcooper.

FWIW the next major of the agent (agent 6, currently in public beta on Linux: https://github.com/DataDog/datadog-agent/) will drop support for sending events from the http_check, which will (incidentally) solve this once and for all.

**Comment by irabinovitch** [comment]
Closing this as agent6 is now long been released.
