### ISSUE TITLE
easy_install chef resource is deprecated and was removed from Chef 13

### ISSUE THREAD

**Issue by iancward** [DataDog/chef-datadog#449]
The ddtrace-python recipe uses the `easy_install` resource that was deprected and removed in Chef 13
https://github.com/DataDog/chef-datadog/blob/master/recipes/ddtrace-python.rb#L6
https://github.com/chef/chef/pull/4860

If this python module is still required, it will probably be necessary to depend on the poise-python cookbok to install it.

**Comment by olivielpeau** [comment]
Hi @iancward, thanks for reporting this, and sorry I didn't look into this earlier.

If possible I'd like to avoid adding a dependency to the whole cookbook in order to support one recipe for a specific integration. I'm tempted to just document that this recipe is not supported on Chef >= 13, and document what code could be typically added to install the `ddtrace` on Chef >= 13.

Let me know what you think @iancward.

(cc @palazzem, since you're the maintainer of the dd-trace-py project)

**Comment by haidangwa** [comment]
@olivielpeau @palazzem This bug is now  showstopper since Chef 12's End-of-Life [announcement](https://www.chef.io/eol-chef12-and-chefdk1/) has been made by Chef (4/30), we need to accelerate Chef 13 support.

**Comment by haidangwa** [comment]
`#easy_install_package` appears in two places. The first is mentioned above, and here's the second: https://github.com/DataDog/chef-datadog/blob/420f03a3521522e23c748175bb4136f038645b60/recipes/dogstatsd-python.rb#L20

**Comment by olivielpeau** [comment]
@haidangwa thanks for the additional info. The `dogstatsd-python` and `ddtrace-python` recipes are not supported with Chef >= 13, I've documented how to work around this in https://github.com/DataDog/chef-datadog/pull/533 if you're currently using one of these recipes, let me know if that helps.

Looking at all the options supported by the `poise-python`, I think it's unwise for the `datadog` cookbook to directly try to use `poise-python` to install python packages: we would have to support various types of python installs (and increase the number of attributes of the `datadog`cookbook to support these options), on top of adding yet another cookbook dependency.

**Comment by haidangwa** [comment]
@olivielpeau Just wanted to report back that the workaround worked for us.

```
       Recipe: my_datadog::default
         * python_package[ddtrace] action install[2018-03-23T16:58:37+00:00] INFO: Processing python_package[ddtrace] action install (tae_datadog::default line 91)
       [2018-03-23T16:58:41+00:00] INFO: python_package[ddtrace] installed ddtrace at 0.11.0
       
           - install version 0.11.0 of package ddtrace
```

**Comment by olivielpeau** [comment]
Thanks! Good to know it worked 👍

**Comment by olivielpeau** [comment]
Closing this issue: absence of support of these recipes in Chef >= 13 has been documented (along with recommended workarounds), in https://github.com/DataDog/chef-datadog/pull/533
