### ISSUE TITLE
Update README with an example for AWS OpsWorks (chef solo?)

### ISSUE THREAD

**Issue by dfithian** [DataDog/chef-datadog#466]
All I had to do in the end to get this working was to provide the node attributes and invoke the recipe by adding the line `include_recipe 'datadog::dd-agent'` at the top of my `install.rb` but it would probably be nice to include that in the README for those not familiar with Chef in the typical context (definitely me).

**Comment by dfithian** [comment]
Happy to add this change myself

**Comment by olivielpeau** [comment]
Hi @dfithian, and thanks for the feedback! Sorry I didn't answer before.

If you have the chance to improve the README with better instructions your contribution would be more than welcome :)
