### ISSUE TITLE
Log directory wrong for windows installs (/var/log)

### ISSUE THREAD

**Issue by borgilb** [DataDog/chef-datadog#470]
Fairly flagrant bug (I think), note this attribute:
default['datadog']['log_file_directory'] = '/var/log/datadog'

So when I deploy this on windows my logging is broken because the logging config points to a place that doesn't exist.

In the attributes file you already have conditional logic for the config dir:
```
if node['platform_family'] == 'windows'
  default['datadog']['config_dir'] = "#{ENV['ProgramData']}/Datadog"
  default['datadog']['agent_name'] = 'DatadogAgent'
else
  default['datadog']['config_dir'] = '/etc/dd-agent'
  default['datadog']['agent_name'] = 'datadog-agent'
end
```

Why not just add the logging dir attribute to this block?

**Comment by mlcooper** [comment]
👍 we're seeing this as well
![capture](https://user-images.githubusercontent.com/9505606/30990545-b47b9754-a46f-11e7-9c0a-18d46af5552f.PNG)

**Comment by bennicholes** [comment]
+1 having this issue as well

**Comment by olivielpeau** [comment]
Fairly flagrant bug indeed, thanks @borgilb for reporting it!

Let me fix this now...
