### ISSUE TITLE
[go-metro] Add Recipe TCP RTT / go-metro integration

### ISSUE THREAD

**Issue by iancward** [DataDog/chef-datadog#478]
Datadog has a go-metro integration (https://docs.datadoghq.com/integrations/tcprtt/) that requires some additional setup, including packages and PCAP settings. It would be nice if a recipe could be added here to handle those items for you.

**Comment by iancward** [comment]
I could probably open a PR for this; however, I don't know if there's a "correct" way to call the setcap command that would not involve running the command every time chef ran.

**Comment by iancward** [comment]
It also looks like upgrading Datadog resets the capabilities on that file.

**Comment by olivielpeau** [comment]
Closing, added in #484, thanks again @iancward!
