### ISSUE TITLE
chef role to install datadog & mongo db

### ISSUE THREAD

**Issue by BhanuCh** [DataDog/chef-datadog#482]
Hello I have following chef role to configure mongo db integration for datadog.
This is not working. Chef runs successfully but mongo integration is not working.

# # Command 
/etc/init.d/datadog-agent info

mongo (unknown)
    ---------------
      - initialize check class [ERROR]: 'mapping values are not allowed in this context\n  in "<byte string>", line 2, column 23'

# # Command
cat /etc/dd-agent/conf.d/mongo.yaml
instances:
  - server: mongodb://:

init_config:
  No init_config details needed
  
mongo.yaml is not getting the configuration required.
  
# # Chef Role

{
 "name": "datadog_mongodb",
 "description": "Datadog MongoDB role",
 "default_attributes": {
   "datadog": {
     "api_key": "abcdwe",
     "mongo": {
       "instances": [
         {
           "server": "mongodb://datadog:password5@localhost:27017",
           "ssl" : "True"
         }
       ]
     }
   }
 },
 "run_list": [
   "recipe[datadog::mongo]"
 ]
}

**Comment by olivielpeau** [comment]
Hi @BhanuCh, thanks for opening this issue.

You can refer to the specific recipe or its template to understand which attributes it expects. In the case of `mongo`, you can refer to https://github.com/DataDog/chef-datadog/blob/v2.12.0/templates/default/mongo.yaml.erb#L3 : it expects a `host` and a `port`, you can probably use `datadog:password@locahost` as the host and `27017` as the port.

Let me know how that goes, thanks!

**Comment by olivielpeau** [comment]
Closing this as I don't think it points to anything broken in the cookbook, @BhanuCh let me know if you still think there's an issue and we can re-open.
