### ISSUE TITLE
Consul recipe missing supported options

### ISSUE THREAD

**Issue by azuretek** [DataDog/chef-datadog#500]
The consul recipe is missing the `self_leader_check` and `network_latency_checks` options.

https://github.com/DataDog/chef-datadog/blob/168fb332ac601a51376a5a73219913443d91619d/templates/default/consul.yaml.erb

**Comment by azuretek** [comment]
I've submitted a PR with the necessary changes to the `consul.yaml.erb` template

https://github.com/DataDog/chef-datadog/pull/501

**Comment by olivielpeau** [comment]
Just merged #501 which addresses this, will be shipped in v`2.14.0`, thanks again @azuretek!
