### ISSUE TITLE
docker / docker_daemon information for datadog-agent version 5.x and version 6.x

### ISSUE THREAD

**Issue by cmessinaclearchannel** [DataDog/chef-datadog#503]
It seems that docker_daemon is no longer recognized as a check by datadog-agent 6.x
Thus the information in the docker.rb and docker_daemon.rb are no longer accurate.

```
node.override['datadog']['docker_daemon']['instances'] = [ 
   ...
]
include_recipe "datadog::docker_daemon"
```

creates the following error:

```
datadog-agent status
...
  Loading Errors
  ==============
    docker_daemon
    -------------
      Core Check Loader:
        Check docker_daemon not found in Catalog
        
      JMX Check Loader:
        check is not a jmx check, or unable to determine if it's so
        
      Python Check Loader:
        No module named docker_daemon

datadog-agent version
Agent 6.0.0-beta.6 - Commit: 19f3a44 - Serialization version: 4.6
...
```

I changed my recipe to use:
```
node.override['datadog']['docker']['instances'] = [ 
   ...
]
include_recipe "datadog::docker"
```

the check now works with datadog-agent 6, and the integration shows up again on the datadog site for this host.

A quick update to the in-line documentation for the docker.rb and docker_daemon.rb recipes would hoepfully make this clear and save others a little time.
Perhaps something along the lines of https://github.com/DataDog/chef-datadog/pull/502

**Comment by olivielpeau** [comment]
Closing this since #502 was merged. Will be released in `2.14.0` (planned for this week). Thanks again @cmessinaclearchannel!
