### ISSUE TITLE
chef_handler::default recipe is deprecated

### ISSUE THREAD

**Issue by ayarmoluk17** [DataDog/chef-datadog#504]
Cookbook version: 2.13.0

When including recipe `datadog::dd-handler` warning is issued during chef run:
```
[2017-12-26T10:46:07+00:00] WARN: chef_handler::default recipe has been deprecated. Use the chef_handler resource instead to define handlers from your own wrapper cookbook.
Recipe: datadog::dd-handler
  * chef_gem[chef-handler-datadog] action install (up to date)
  * chef_handler[Chef::Handler::Datadog] action enable (up to date)
```

**Comment by olivielpeau** [comment]
Hi @ayarmoluk17, thanks for reporting this!

Looks like the `chef_handler` resource was added in v`1.4.0` of the chef_handler cookbook (see https://github.com/chef-cookbooks/chef_handler/blob/master/CHANGELOG.md#v140-2016-05-13).

I think it's a good idea to increase our version constraint on that cookbook to `~>1.4.0`, #396 would be a good base to start from. I'll work on that if I have some time (or if the warning becomes a breaking change on `chef_handler`'s side), but feel free to contribute if you have the chance!

**Comment by iennae** [comment]
@olivielpeau I wouldn't recommend pinning to 1.4.0 especially with the 2.1.1 version including the fix for Chef 13 compatibility.

**Comment by olivielpeau** [comment]
@iennae you're right, thanks for mentioning this, I should've written `>=1.4.0`, we definitely want to allow versions of `chef_handler` that are compatible with Chef 13.

(as an aside, the metadata currently allows any `chef_handler` version `>= 1.1 ` https://github.com/DataDog/chef-datadog/blob/v2.15.0/metadata.rb#L26)

**Comment by remeh** [comment]
Thanks to both of you for your contribution! Having removed the `include_recipe` in https://github.com/DataDog/chef-datadog/pull/597 should remove the warning mentioned here.
We're aware of the deprecation of chef_handler but unfortunately, as mentioned in the PR we still need this dep for Chef 12 / 13 for now.
The deprecation warning mentioned here being removed by the PR, I'm closing this issue 👍
