### ISSUE TITLE
`repository` recipe requires `dirmngr` package on Debian 9

### ISSUE THREAD

**Issue by olivielpeau** [DataDog/chef-datadog#506]
The `datadog::repository` recipe uses `apt-key`. On Debian 9, it works only if the `dirmngr` package is installed.

The cookbook should make sure `dirmngr` is installed on Debian 9 before using `apt-key`

**Comment by renchap** [comment]
According to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=858238#10, the correct way to fix this is by no longer using the deprecated `apt-key` and putting the keys in `trusted.gpg.d`.

**Comment by olivielpeau** [comment]
Initially fixed in https://github.com/DataDog/chef-datadog/pull/629, and the correct fix for newer distros was implemented in https://github.com/DataDog/chef-datadog/pull/796, closing
