### ISSUE TITLE
Agent6 recipe does not create config directory

### ISSUE THREAD

**Issue by cyraxx** [DataDog/chef-datadog#509]
After enabling `agent6`, agent installation fails with:

```
Chef::Exceptions::EnclosingDirectoryDoesNotExist
------------------------------------------------
Parent directory /etc/datadog-agent does not exist.

Resource Declaration:
---------------------
# In /var/lib/aws/opsworks/cache.stage2/cookbooks/datadog/recipes/_agent6_config.rb
 
28: template trace_agent_config_file do
29:   def conf_template_vars
30:     {
31:       :api_keys => [Chef::Datadog.api_key(node)],
32:       :dd_urls => [node['datadog']['url']]
33:     }
34:   end
35:   variables(
```

Looking at `recipes/dd-agent.rb`, the agent5 branch explicitly has a `directory` resource to create the config directory, however the agent6 branch only includes `_agent6_config.rb` which does not.

Using Chef 11 for the record although I don't think the behavior of the `template` resource changed between versions.

**Comment by cyraxx** [comment]
The `conf.d` subdirectory is affected as well.

**Comment by olivielpeau** [comment]
Hi @cyraxx, thanks for opening this issue! The `datadog-agent` package is supposed to be installed first and create that directory, so the use of the `directory` resource shouldn't be needed.

Can you check that the installation of the Agent 6 went fine on that node (and, in particular, that an Agent 5 wasn't installed instead)? Do the chef-client logs show anything unusual on the `package[datadog-agent]` resource?

Also, any information on the value of [these attributes](https://github.com/DataDog/chef-datadog/blob/v2.13.0/attributes/default.rb#L46-L50) on your node would be helpful

**Comment by cyraxx** [comment]
Unfortunately I don't have the logs from the failed attempt anymore.

I just tried on a new instance and indeed, on this machine the recipe ran without errors. On the machine that had the error agent version 5 was installed first and then upgraded to agent 6 by setting the `agent6` attribute and running the recipe again. Maybe that's what causes the issue.

Of the attributes you mentioned we only have `agent6` set to `true` and the others left on default.

Since I can't seem to reproduce the issue anymore feel free to close.

**Comment by olivielpeau** [comment]
Ok, thanks @cyraxx for the explanation, I'm not sure what could've caused this error (upgrades from Agent 5 to 6 have worked fine on our internal environments).

It might help to explicitly set both the `agent_version` (-> agent 5 version) and `agent6_version` (-> agent 6 version) attributes to make sure that the `package` resource actually installs the version you want. You can set both of these attributes on all your nodes, and the cookbook will install either the agent 5 or the agent 6 version on each node depending on whether `agent6` is set to `true` or `false` on that node.

Anyway, I'll go ahead and close this, feel free to re-open if you run into this again.

**Comment by kmf** [comment]
We are affected by this issue on one of our nodes, must I open a new issue @olivielpeau
