### ISSUE TITLE
cassandra.yaml configuration outdated

### ISSUE THREAD

**Issue by cikin** [DataDog/chef-datadog#510]
https://github.com/DataDog/chef-datadog/blob/master/templates/default/cassandra.yaml.erb 
is not reflecting the metrics captured in
https://github.com/DataDog/integrations-core/blob/master/cassandra/conf.yaml.example

**Comment by olivielpeau** [comment]
Hi @cikin, thanks for reporting this!

You're right this needs updating. I'll work on adding this to the next minor release.
