### ISSUE TITLE
Agent Checks Not Installed on Ubuntu

### ISSUE THREAD

**Issue by rdickey-r7** [DataDog/chef-datadog#512]
Starting in version 1:5.22.0-1 the ubuntu install doesn't create or populate the /opt/datadog-agent/agent/checks.d/ directory.

According to https://github.com/datadog/integrations-core this is the newly intended behavior.  This behavior is not reflected in the chef cookbook, and should be.  As in, the agent checks should be installed in the new way by default in the chef cookbook, whatever that means.

**Comment by olivielpeau** [comment]
Hi @rdickey-r7!

The `datadog-agent` package (including version `1:5.22.0-1`) still includes the core checks from [`integrations-core`](https://github.com/datadog/integrations-core) by default. So the cookbook doesn't need to do anything specific for these integrations to be installed.

That said, we are soon going to introduce a new way to upgrade the checks individually (if for instance you want to keep the same version of the Agent but run a newer version of a specific check). We'll update the cookbook to allow using this new feature (when it's ready), but for now this cookbook doesn't require any changes.

I'll go ahead and close the issue, but let me know if my explanation was clear (or not), or if you have any questions/comments.
