### ISSUE TITLE
Agent 6 doesn't install on Windows

### ISSUE THREAD

**Issue by rlaveycal** [DataDog/chef-datadog#524]
There are several issues with installing Agent 6 on Windows
1. Dependent service restart (fixed by #520 )
1. Config file security not setting Windows values
1. No default for Windows config directory

The config directory for integrations has also changed for Agent 6 to be a sub directory of conf.d (see https://github.com/DataDog/datadog-agent/blob/master/docs/agent/changes.md#checks-configuration-files)

**Comment by olivielpeau** [comment]
Thanks @rlaveycal for the detailed list, very helpful!

I've left a comment on your PR about the sub-directory of conf.d.

The cookbook should also pull the Agent 6 version on Windows from the `agent6_version` attribute to be consistent with the Linux behavior. I'll add this shortly.
