### ISSUE TITLE
Is there 6.1 support yet?

### ISSUE THREAD

**Issue by benorgil** [DataDog/chef-datadog#537]
Does the cookbook support 6.1 yet? Where in the cookbook can i see the latest agent version it supports?

**Comment by olivielpeau** [comment]
Hey @benorgil, sorry for the very late reply.

The latest version of the Agent should always be supported by the latest released version of the cookbook. I've clarified the README a bit in https://github.com/DataDog/chef-datadog/commit/dd428290f2151bdcd5ef01631f290efbdd380543, let me know if you have any feedback
