### ISSUE TITLE
Replace easy_install resource with something Chef 13 proof

### ISSUE THREAD

**Issue by stefanwb** [DataDog/chef-datadog#539]
Deprecation: Easy Install Resource (CHEF-6)

The Python community recommends that users prefer pip rather than easy_install to install python packages.

The easy_install resource was deprecated in 12.10, and will be removed in Chef 13.

Remediation
There is no built in replacement for easy_install in Chef. The poise-python cookbook provides a set of resources for managing Python installations.

https://docs.chef.io/deprecations_easy_install.html

**Comment by olivielpeau** [comment]
As discussed in https://github.com/DataDog/chef-datadog/pull/567, we'll:

* deprecate the recipes that use `easy_install` in v2.17
* remove them in v3.0
* document how to use the `poise-python` cookbook to install these python packages

**Comment by remeh** [comment]
That has been done by #591 and #585. I'm closing this now 👍
