### ISSUE TITLE
Problem installing agent6 on ubuntu 14.04 due to upstart

### ISSUE THREAD

**Issue by sylvaintremblay666** [DataDog/chef-datadog#542]
Installing agent6 on ubuntu 14.04 doesn't work due to upstart.

A bug have already been fixed regarding this for RHEL / Amazon Linux on version 2.14.0 / 2018-02-27, but it doesn't include Ubuntu.

In _recipies/dd-agent.rb_ around line 106, a case for ubuntu 14.04 should be added. To test locally, I simply forced "service_provider = Chef::Provider::Service::Upstart" which made the installation succeed.

**Comment by olivielpeau** [comment]
Hi @sylvaintremblay666, thanks for opening this issue!

Chef should detect `upstart` as the default service provider on Ubuntu 14.04 (as upstart _is_ the default init system on Ubuntu 14.04). What's your version of Chef? Is there anything specific about your init system setup on your Ubuntu 14.04 environment?

**Comment by sylvaintremblay666** [comment]
Hi @olivielpeau ,

I'm running on AWS with OpsWorks. Chef is a little old (11.10.4).
Running on this AMI : ubuntu/images/hvm/ubuntu-trusty-14.04-amd64-server-20170811 (ami-845367ff)
Nothing special about the machine / its init system.

Thanks a lot,

Sylvain

**Comment by mshepet** [comment]
+1
I ran into the exact same issue with agent6 on OpsWorks w/ Chef 11.10 and Ubuntu 14.04. Used sylvaintremblay666's solution to force service_provider = Chef::Provider::Service::Upstart in dd-agent.rb and that solved the installation error.

**Comment by remeh** [comment]
Hello! Indeed, Chef < 11.14 doesn't use the correct service provider for Ubuntu. This PR has fixed it. https://github.com/DataDog/chef-datadog/pull/551 and it'll be available in release `2.18.0`.
