### ISSUE TITLE
How to include the IP address instead of localhost in elasticsearch integration

### ISSUE THREAD

**Issue by deppfx** [DataDog/chef-datadog#552]
We have our Elasticsearch running on the IP address and not on open interface (0.0.0.0) or localhost. This renders the recipe unusable as it only accepts strings. Is there a way for us to change it

from:

```
[root@ip-x-x-x-x ~]# cat /etc/dd-agent/conf.d/auto_conf/elastic.yaml 
init_config:
instances:
  - url: "http://localhost:9200"
```
to
```
[root@ip-x-x-x-x ~]# cat /etc/dd-agent/conf.d/auto_conf/elastic.yaml 
init_config:
instances:
  - url: "http://<ipaddress>:9200"
```

https://github.com/DataDog/chef-datadog/blob/master/recipes/elasticsearch.rb

**Comment by olivielpeau** [comment]
Hi @deppfx,

Sorry for the late reply.

This should work by setting your attributes like the following:

```ruby
node['datadog']['elasticsearch']['instances'] = [{
  :url => 'http://<ipaddress>:9200'
}]
```

I'll go ahead and close this issue, but feel free to comment if you're still having issues!
