### ISSUE TITLE
ignore_resources unable to be added via extra_config/apm_config

### ISSUE THREAD

**Issue by spencermpeterson** [DataDog/chef-datadog#559]
Running into issues populating the ignore_resources directive (possibly) due to the brackets. Escaping the internal quotes allows the string to properly populate into chef as the screenshot shows; however during a chef run, the string is written with single quotes surrounding the brackets, preventing datadog-agent from running. Using chef-12.22.5-1

chef env attributes:
`    "datadog": {
      "agent6": true,
      "agent6_package_action": "upgrade",
      "enable_trace_agent": true,
      "trace_env": "nonprod",
      "extra_config": {
        "apm_config": {
          "ignore_resources": "[\"GET /env\", \"GET /info\", \"GET /health\"]"
        }
      }`

datadog.yml:
<img width="445" alt="screen shot 2018-09-12 at 17 28 58" src="https://user-images.githubusercontent.com/28761102/45456711-684acf80-b6b1-11e8-8320-d0aab31075b8.png">

chef screenshot:
<img width="412" alt="screen shot 2018-09-12 at 17 19 56" src="https://user-images.githubusercontent.com/28761102/45456381-279e8680-b6b0-11e8-9779-7b3ef51bd7f7.png">

**Comment by olivielpeau** [comment]
Hi @spencermpeterson, sorry for the late reply here.

`ignore_resources` expect a _list_ (see https://github.com/DataDog/datadog-agent/blob/6.6.0/pkg/config/config_template.yaml#L668-L671) as value, whereas you're currently defining a _string_ value. So, in ruby, you should define the value as a list as well, i.e.:

```rb
# [...]
{ "ignore_resources": ["GET /env", "GET /info", "GET /health"] }
```

I'll go ahead and close this issue, but feel free to comment here if this doesn't help, thanks!

**Comment by spencermpeterson** [comment]
@olivielpeau thank you for your response. I think I misunderstood the wording from the configuration and assumed that we wanted the ignored resources to be inside the brackets in the datadog.yaml file. I followed your example and now get an output that looks a bit more traditional:

````
# Generated by Chef, local modifications will be overwritten

---
apm_config:
  ignore_resources:
  - GET /env
  - GET /info
  - GET /health
````

Thanks again!

**Comment by olivielpeau** [comment]
Great, thanks for confirming this worked 👍
