### ISSUE TITLE
tomcat template formatting issue

### ISSUE THREAD

**Issue by olivielpeau** [DataDog/chef-datadog#574]
The last 2 `include`s in the `tomcat` template are missing the `attribute` key, which makes JMXFetch log errors and fail to collect the related beans: https://github.com/DataDog/chef-datadog/blob/v2.16.1/templates/default/tomcat.yaml.erb#L63-L78\

(reported on the community Slack, I'll address this in 2.17.0)

**Comment by remeh** [comment]
https://github.com/DataDog/chef-datadog/pull/583 is fixing this issue, I'm closing it.
