### ISSUE TITLE
Add support for vault monitoring

### ISSUE THREAD

**Issue by gevorg15** [DataDog/chef-datadog#581]
Similar to how consul monitoring is done. It would be nice to have support for monitoring HashiCorp vault.

Datadog already supports this but there is no recipe yet in this cookbook.

**Comment by remeh** [comment]
Hello @gevorg15 

You're absolutely right! Thanks to this recently merged PR https://github.com/DataDog/chef-datadog/pull/555 it is now included in master and it will be part of release `2.17.0`.

I'm closing the issue, feel free to re-open it if you still have any concern about this.
