### ISSUE TITLE
datadog agnet6 failing while using amazonlinux in test-kitchen

### ISSUE THREAD

**Issue by isukapalli** [DataDog/chef-datadog#637]
Convergence failing when using kitchen-docker with the below error.
```
---- Begin output of /sbin/start datadog-agent ----
           STDOUT:
           STDERR: start: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
```
Agent5 works fine and not giving any error.

cookbook version: 3.2.0
image: amazonlinx 2018.03

**Comment by remeh** [comment]
Hello @isukapalli ,
This is because while running in a Docker container using kitchen-docker, it's most likely that there is no init system running (Upstart, systemd, ...), thus the cookbook can't properly try to start/stop the Agent.
If possible, you can switch to the Vagrant provider.
