### ISSUE TITLE
chef_handler dependency resulting a WARNING

### ISSUE THREAD

**Issue by gangadhar01a** [DataDog/chef-datadog#682]
We have upgraded chef client to 15 and on a run the following warning message showing up

 WARN: Resource chef_handler from the client is overriding the resource from a cookbook. Please upgrade your cookbook or remove the cookbook from your run_list.

Our cookbook's metadata.rb has a dependency on datadog cookbook which has dependency on chef_handler cookbook.  Chef client 14+ natively included the chef handler cookbook, do you have any plans to exclude chef_hanlder cookbook in future release?

**Comment by jeremy-lq** [comment]
@gangadhar01a  We're currently tracking this feature request. Please open a [support ticket](https://docs.datadoghq.com/help/) so we can add you to the card and notify you when it's been completed.
