### ISSUE TITLE
Incorrect comments re. value of skip_ssl_validation

### ISSUE THREAD

**Issue by jaxi** [DataDog/chef-datadog#692]
https://github.com/DataDog/chef-datadog/blob/e0451e78b747e307e609f5bb1f4ed9d45b0e51fa/attributes/default.rb#L250 suggests that `skip_ssl_validation` "accepted values 'yes' or 'no'", however in [DD agent proxy config documentation](https://docs.datadoghq.com/agent/proxy/?tab=agentv6v7#datadog-agent-configuration), the value is expected to be a boolean

```
skip_ssl_validation: true
```

I initially gave `default['datadog']['web_proxy']['skip_ssl_validation'] = 'yes'` a go, which causes TLS handshake error with the proxy server, on the other hand `default['datadog']['web_proxy']['skip_ssl_validation'] = true` works as expected.

Notes that correct this also potentially leads https://github.com/DataDog/chef-datadog/blob/e0451e78b747e307e609f5bb1f4ed9d45b0e51fa/templates/default/datadog.conf.erb#L14 to be change into

```
<% unless node['datadog']['web_proxy']['skip_ssl_validation'].nil? -%>
...
```

**Comment by jaxi** [comment]
PS: if it is regarded as a real issue I'm more than happy to submit a PR to fix it up :)

**Comment by kbogtob** [comment]
Thanks for raising the issue! I can confirm the issue you are describing for recent agents, but I suppose the yes/no values were used by older agent versions. I'll check and confirm you if want to work on a PR :).

**Comment by kbogtob** [comment]
The values 'yes' / 'no' were indeed needed by agent v5 (https://docs.datadoghq.com/agent/proxy/?tab=agentv5#datadog-agent-configuration). So the cookbook must support both.
@jaxi could you propose a PR for that? Your contribution would be greatly appreciated.

**Comment by albertvaka** [comment]
Agent 5 can also take true/false [1], so we should simply change it to print the boolean.

[1] https://github.com/DataDog/dd-agent/blob/master/config.py#L598

**Comment by jaxi** [comment]
I see. In this case a sane approach might simply be change the default attribute into

```
default['datadog']['web_proxy']['skip_ssl_validation'] = false
```

Right now GH keep throwing me 500 on forking the repo, will submit a PR once it comes back to normal :)

**Comment by jaxi** [comment]
@albertvaka @kbogtob pull request ready in https://github.com/DataDog/chef-datadog/pull/693. Please let me know what you think.

**Comment by albertvaka** [comment]
Fixed in https://github.com/DataDog/chef-datadog/pull/693
