### ISSUE TITLE
Datadog cookbook failing on Windows Server 2019

### ISSUE THREAD

**Issue by irynadiudiuk** [DataDog/chef-datadog#697]
Hi there,

We need to install the latest version of Datadog agent on Windows 2019.

I think the issue I am having might have something to do with the following issue:
https://github.com/DataDog/chef-datadog/issues/536

I have not pinned any version at this point.
The version that is being installed is the latest release of datadog version 7, which is at the moment version "7.17.2.1".
After the attributes for username and password are read, the job returns error 1603.
Should pinning the major version to: default['datadog']['agent_major_version'] = '7' to be a fix? Is this something that is considered a known issue?

windows server 2019
chef-client-15.5.17-1-x64.msi
cookbook 'datadog', '4.2.0

Below is the full error trace:
    windows-2019:   * windows_env[DDAGENTUSER_NAME] action create[2020-03-02T13:52:49+00:00] INFO: Processing windows_env[DDAGENTUSER_NAME] action create (datadog::_install-windows line 134)
    windows-2019: [2020-03-02T13:52:50+00:00] INFO: windows_env[DDAGENTUSER_NAME] created
    windows-2019:   * windows_env[DDAGENTUSER_PASSWORD] action create[2020-03-02T13:52:50+00:00] INFO: Processing windows_env[DDAGENTUSER_PASSWORD] action create (datadog::_install-windows line 139)
    windows-2019: [2020-03-02T13:52:50+00:00] INFO: windows_env[DDAGENTUSER_PASSWORD] created
    windows-2019:   * windows_package[Datadog Agent] action install[2020-03-02T13:52:50+00:00] INFO: Processing windows_package[Datadog Agent] action install (datadog::_install-windows line 145)
* windows_package[Datadog Agent] action install[2020-03-02T13:52:50+00:00] INFO: Processing windows_package[Datadog Agent] action install (datadog::_install-windows line 145)

    windows-2019:     Error executing action `install` on resource 'windows_package[Datadog Agent]'
    windows-2019:     **Mixlib::ShellOut::ShellCommandFailed**
    windows-2019:     ------------------------------------
    windows-2019:     Expected process to exit with [0, 3010], but received '1603'
    windows-2019:     ---- Begin output of msiexec /qn /i "c:\windows\temp\packer-chef-solo\local-mode-cache\cache\ddagent-cli.msi"  /norestart ALLUSERS=1 DDAGENTUSER_NAME=%DDAGENTUSER_NAME% DDAGENTUSER_PASSWORD=%DDAGENTUSER_PASSWORD% ----
    windows-2019:     STDOUT:
    windows-2019:     STDERR:
    windows-2019:     ---- End output of msiexec /qn /i "c:\windows\temp\packer-chef-solo\local-mode-cache\cache\ddagent-cli.msi"  /norestart ALLUSERS=1 DDAGENTUSER_NAME=%DDAGENTUSER_NAME% DDAGENTUSER_PASSWORD=%DDAGENTUSER_PASSWORD% ----
    windows-2019:     Ran msiexec /qn /i "c:\windows\temp\packer-chef-solo\local-mode-cache\cache\ddagent-cli.msi"  /norestart ALLUSERS=1 DDAGENTUSER_NAME=%DDAGENTUSER_NAME% **DDAGENTUSER_PASSWORD=%DDAGENTUSER_PASSWORD% returned 1603**
    windows-2019:
    windows-2019:     Resource Declaration:
    windows-2019:     ---------------------
    windows-2019:     # In c:/windows/temp/packer-chef-solo/local-mode-cache/cache/cookbooks/datadog/recipes/_install-windows.rb
    windows-2019:
    windows-2019:     145: windows_package 'Datadog Agent' do # ~FC009
    windows-2019:     146:   source temp_file
    windows-2019:     147:   installer_type resolved_installer_type
    windows-2019:     148:   options install_options
    windows-2019:     149:   timeout node['datadog']['windows_msi_timeout']
    windows-2019:     150:   action :install
    windows-2019:     151:   # Before 3.0.0, we adviced users to use the windows cookbook ~> 1.38.0,
    windows-2019:     152:   # we should probably keep the compatibilty for some time.
    windows-2019:     153:   if respond_to?(:returns)
    windows-2019:     154:     returns [0, 3010]
    windows-2019:     155:   else
    windows-2019:     156:     success_codes [0, 3010]
    windows-2019:     157:   end
    windows-2019:     158:   not_if do
    windows-2019:
    windows-2019:     Compiled Resource:
    windows-2019:     ------------------
    windows-2019:     # Declared in c:/windows/temp/packer-chef-solo/local-mode-cache/cache/cookbooks/datadog/recipes/_install-windows.rb:145:in `from_file'
    windows-2019:
    windows-2019:     windows_package("Datadog Agent") do
    windows-2019:       package_name "Datadog Agent"
    windows-2019:       action [:install]
    windows-2019:       default_guard_interpreter :default
    windows-2019:       declared_type :windows_package
    windows-2019:       cookbook_name "datadog"
    windows-2019:       recipe_name "_install-windows"
    windows-2019:       installer_type :msi
    windows-2019:       source "c:\\windows\\temp\\packer-chef-solo\\local-mode-cache\\cache\\ddagent-cli.msi"
    windows-2019:       options "/norestart ALLUSERS=1 DDAGENTUSER_NAME=%DDAGENTUSER_NAME% DDAGENTUSER_PASSWORD=%DDAGENTUSER_PASSWORD%"
    windows-2019:       returns [0, 3010]
    windows-2019:       timeout 900
    windows-2019:       version "7.17.2.1"
    windows-2019:       not_if { #code block }
    windows-2019:     end
    windows-2019:
    windows-2019:     System Info:
    windows-2019:     ------------
    windows-2019:     chef_version=15.5.17
    windows-2019:     platform=windows
    windows-2019:     platform_version=10.0.17763
    windows-2019:     ruby=ruby 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32]
    windows-2019:     program_name=c:/opscode/chef/bin/chef-solo
    windows-2019:     executable=c:/opscode/chef/bin/chef-solo
    windows-2019: Running handlers:
    windows-2019: [2020-03-02T13:54:51+00:00] ERROR: Running exception handlers
    windows-2019: Running handlers complete
    windows-2019: [2020-03-02T13:54:51+00:00] ERROR: Exception handlers complete
    windows-2019: Chef Infra Client failed. 226 resources updated in 23 minutes 16 seconds
    windows-2019: [2020-03-02T13:54:51+00:00] INFO: Windows environment vars cleanup started.
    windows-2019: [2020-03-02T13:54:51+00:00] INFO: Processing windows_env[DDAGENTUSER_NAME] action delete (datadog::_install-windows line 168)
    windows-2019: [2020-03-02T13:54:51+00:00] INFO: windows_env[DDAGENTUSER_NAME] deleted
    windows-2019: [2020-03-02T13:54:51+00:00] INFO: Processing windows_env[DDAGENTUSER_PASSWORD] action delete (datadog::_install-windows line 173)
    windows-2019: [2020-03-02T13:54:52+00:00] INFO: windows_env[DDAGENTUSER_PASSWORD] deleted
    windows-2019: [2020-03-02T13:54:52+00:00] INFO: Windows environment vars cleanup finished.
    windows-2019: Recipe: datadog::_install-windows
    windows-2019:   * windows_env[DDAGENTUSER_NAME] action delete
    windows-2019:
    windows-2019:   * windows_env[DDAGENTUSER_PASSWORD] action delete
    windows-2019:
    windows-2019: [2020-03-02T13:54:52+00:00] FATAL: Stacktrace dumped to c:/windows/temp/packer-chef-solo/local-mode-cache/cache/chef-stacktrace.out
    windows-2019: [2020-03-02T13:54:52+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
    windows-2019: [2020-03-02T13:54:52+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: windows_package[Datadog Agent] (datadog::_install-windows line 145) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0, 3010], but received '1603'
    windows-2019: ---- Begin output of msiexec /qn /i "c:\windows\temp\packer-chef-solo\local-mode-cache\cache\ddagent-cli.msi"  /norestart ALLUSERS=1 DDAGENTUSER_NAME=%DDAGENTUSER_NAME% DDAGENTUSER_PASSWORD=%DDAGENTUSER_PASSWORD% ----
    windows-2019: STDOUT:
    windows-2019: STDERR:
    windows-2019: ---- End output of msiexec /qn /i "c:\windows\temp\packer-chef-solo\local-mode-cache\cache\ddagent-cli.msi"  /norestart ALLUSERS=1 DDAGENTUSER_NAME=%DDAGENTUSER_NAME% DDAGENTUSER_PASSWORD=%DDAGENTUSER_PASSWORD% ----
    windows-2019: Ran msiexec /qn /i "c:\windows\temp\packer-chef-solo\local-mode-cache\cache\ddagent-cli.msi"  /norestart ALLUSERS=1 DDAGENTUSER_NAME=%DDAGENTUSER_NAME% DDAGENTUSER_PASSWORD=%DDAGENTUSER_PASSWORD% **returned 1603**

Please let me know if you need more information from my side.

**Comment by kbogtob** [comment]
Hello @irynadiudiuk! 
Thanks for raising the issue. It's actually a bug introduced in #691 and #694 and currently reverted by #699. You can now use the v4.2.1 that has the reverted commits. 

We will work on the issues of #691 and #694 to allow installation without credentials.

**Comment by irynadiudiuk** [comment]
Hi @kbogtob,

Thank you so much for your reply. I will try with v4.2.1 now and let you know.

**Comment by irynadiudiuk** [comment]
@kbogtob,

I have tried with the new version of a cookbook:

'windows-2019: Vendoring datadog (4.2.1) to ../../packaged-cookbooks/datadog'

At the moment, it seems that the error persists:
FATAL: Mixlib::ShellOut::ShellCommandFailed: windows_package[Datadog Agent] (datadog::_install-windows line 112) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0, 3010], but received '1603'

windows-2019: ---- End output of msiexec /qn /i "c:\windows\temp\packer-chef-solo\local-mode-cache\cache\ddagent-cli.msi"  /norestart ALLUSERS=1 DDAGENTUSER_NAME=WORKGROUP\ddagentuser DDAGENTUSER_PASSWORD=******$really_strong_password****
returned 1603

Could you please suggest what else I could try here? I wonder if the name of the user is indicated correctly? (this is a stand-alone instance that has a default 'WORKGROUP' instead of the domain)

chef-client-15.5.17

**Comment by albertvaka** [comment]
If this is not part of a domain, you should be able to not specify a user and password, so the installer creates one for you. If that doesn't fix the issue, we will probably need the installer logs (they are in `%TEMP%\MSI<random_sequence>.log​`), since `1603` is a rather generic installer error. Please open a support ticket and we'll pickup from there.

**Comment by irynadiudiuk** [comment]
Hi @albertvaka and @kbogtob,

I am happy to let you know that when I left the default values ('nil') for DDAGENTUSER_NAME and DAGENTUSER_PASSWORD I was able to install ddagent successfully.
The only thing that I needed to specify was an 'api_key' attribute.

Thank you for your help, it is much appreciated!
