### ISSUE TITLE
Cannot access examples for Windows Event Log

### ISSUE THREAD

**Issue by Swampcritter** [DataDog/chef-datadog#713]
Per the following recipe file:
https://github.com/DataDog/chef-datadog/blob/master/recipes/win32_event_log.rb

It has in it's comments to look over at:
``
@see https://github.com/DataDog/integrations-core/blob/master/win32_event_log/conf.yaml.example for details
``

However it's not possible to get there as it gives a 404 error.

**Comment by albertvaka** [comment]
Indeed. Let me fix the broken link. Thanks for reporting this :)
