### ISSUE TITLE
No way to configure `env` in agent's main configuration file

### ISSUE THREAD

**Issue by fabiomsouto** [DataDog/chef-datadog#758]
Hey,

In the documentation for Unified Service Tagging, for system metrics (https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/?tab=systemmetrics), you require the configuration of a `env` property in the agent's main configuration file (`datadog.yaml`), but it seems this parameter is not configurable via this chef recipe. I had a look at https://github.com/DataDog/chef-datadog/blob/master/templates/default/datadog.yaml.erb and I could not find the `env` property at the root of the file, only under APM configuration (which is for a different purpose).

I was able to confirm that by adding it this configuration manually, the instance was associated to the service correctly, as expected.

Cheers.

**Comment by albertvaka** [comment]
I've opened #759 to add this setting. Note, however, that you can add any setting you want to end up in `datadog.yaml` as key-value pairs under `node['datadog']['extra_config']`. This way you don't have to wait for my change to get merged and released :)

**Comment by fabiomsouto** [comment]
Thank you @albertvaka, was unaware of this!
I can see the changes are already merged in, which is awesome, cheers!

I'm closing this issue then.
