### ISSUE TITLE
Breaking change introduced in version 4.10.0 - network monitoring

### ISSUE THREAD

**Issue by lchayoun** [DataDog/chef-datadog#798]
In this PR, the network monitoring attribute was changed, breaking existing configurations:
https://github.com/DataDog/chef-datadog/pull/784/files

**Comment by albertvaka** [comment]
The PR should just add new fields, so we assumed that wouldn't be a breaking change. Is that causing you problems? What errors do you get because of that?

**Comment by lchayoun** [comment]
You can see this comment:
https://github.com/DataDog/datadog-agent/blob/140a4ee164261ef2245340c50371ba989fbeb038/releasenotes/notes/system-probe-add-network-enable-flag-d08ed22107446437.yaml

It is specifying that adding the `network_config` is causing the network to be disabled.
Without it, when the system probe was enabled, the network monitoring was enabled as well
