### ISSUE TITLE
integration resource should notify a restart of the agent after installing a new version

### ISSUE THREAD

**Issue by lchayoun** [DataDog/chef-datadog#805]
As documented here: https://docs.datadoghq.com/agent/guide/integration-management/#install
"After upgrading, restart your Agent to begin using the newly installed integration"

The issues is, that after upgrading an agent version, all the integration conf files are the same so the agent is not restarted after installing the new agent version and the integration on it.

Same issue occurs when running the cookbook on a new instance, the agent default version is running instead of the newly installed version

**Comment by lchayoun** [comment]
@albertvaka Any schedule for a new release?

**Comment by albertvaka** [comment]
Hi @lchayoun! We should release a new version soon, hopefully this week :)
