### ISSUE TITLE
Support cookbook renaming

### ISSUE THREAD

**Issue by lchayoun** [DataDog/chef-datadog#809]
In many places there is `include_recipe` with reference to `datadog` cookbook.
To support cookbook renaming they should use `::<recipe>`

**Comment by lchayoun** [comment]
Will there be another release with this fix? currently I'm unable to test the last version with the repository change

**Comment by albertvaka** [comment]
I'm going to make a new release now @lchayoun, thanks for your patience and thanks again for your patches :)

**Comment by lchayoun** [comment]
Thanks! Used it now, working great.
