### ISSUE TITLE
chef_handler dependency deprecated

### ISSUE THREAD

**Issue by ericmansa** [DataDog/chef-datadog#872]
This issue tracker is primarily used to track bugs in the scripts. For feature requests, please contact [Datadog support](http://docs.datadoghq.com/help/) and share your ideas with them.
hi could you removed for your dependenccies fo this cookbook the chef_handler which is a deprecated cookbook
thx 
regards eric 
Thanks!

**Comment by amenasria** [comment]
Hey @ericmansa !

Nice catch ! We are working on it and will remove the use of `chef_handler` cookbook for Chef >= 14.

We will keep it for Chef < 14 though as we also support old Chef versions ! 

Thanks for reporting this !

**Comment by amenasria** [comment]
PR is merged ! 🧑🏻‍🍳
